### PR TITLE
refactor: use svg `paint-order` for halo effect

### PR DESCRIPTION
**Pull request by marcelgerber**
Since @sophiamersmann has very helpfully found this great svg property, I decided to use it right away for the existing "halo" effects we have.

This PR is expected to have a large SVG diff, namely for all scatter plots and the few charts that have a comparison line. I will randomly check some SVGs from the diff to check that they are behaving as expected.

### CODE REVIEW

**Comment by marcelgerber** [comment]
Okay, one problem that just occurred to me is that this will break entirely in [(very) old browsers](https://caniuse.com/mdn-css_properties_paint-order); this is what this looks like in IE11 😢:
image

That's a bit of a bummer, since we're often using SVGs as a fallback in old browsers that cannot display our interactive content.

Other TODOs:
- [ ] Check that our own svg-to-png library `sharp` renders this correctly
- [ ] Check that Wikipedia's svg-to-png renders this correctly

**Comment by marcelgerber** [comment]
Okay, since both legacy browsers and Wikipedia don't support this property, I'm gonna put this on halt for now.
There are tactics that could still work - in particular, the `@supports` CSS property to only enable this when supported. See here: https://www.oreilly.com/content/elegant-outlines-with-svg-paint-order/

**Comment by ikesau** [comment]
Looks like we'll have to close this one for the moment right @marcelgerber ?

Should we make a ticket to circle back to this when we can investigate @supports better, or just play a dirge and let it drift out to sea?

**Comment by marcelgerber** [comment]
Yeah, I think it's sadly a "drift to sea" scenario here.

Our SVGs are currently pretty much only using inline CSS styles (and SVG attributes), and I'm pretty sure that `@supports` cannot be used in inline styles but only in proper CSS or `<style>` blocks.

So, that would mean injecting a `<style>` block into all svgs, and then putting a class name or something on all elements that should have a halo effect - and that's quite some effort I think.
But yeah, if you feel like you're up for it then go for it!

**Pull request closed without merging**
