### PR TITLE
Dev: refactor scripts into units. Now baking is a 21 step process

### PR DESCRIPTION
**Pull request by breck7**
It's still a little ugly how it writes scripts and then runs those on the server, perhaps just sending the SSH commands is the way to go. (Although I think ideally the way to go is just run the whole bake locally and then push to Netlify from your dev machine).

### CODE REVIEW

**Comment by MarcelGerber** [comment]
> (Although I think ideally the way to go is just run the whole bake locally and then push to Netlify from your dev machine).

Re that: we need to at least run a Webpack build etc. on the respective server either way, since that's needed for the admin server.

**Comment by breck7** [comment]
> we need to at least run a Webpack build etc. on the respective server either way, since that's needed for the admin server.

Would it be though? Seems to me like nothing should require a webpack build on a remote server.

**Comment by breck7** [comment]
I think we should be able to simplify things so that setting up a staging server is as simple as ~:

```
git clone owid-grapher
yarn install
git clone owid-content
yarn buildtsc
yarn startAdminServer
```

**Comment by MarcelGerber** [comment]
> Would it be though? Seems to me like nothing should require a webpack build on a remote server.

I think we would still need it to generate `admin.js` and some CSS files, which are needed for the admin interface.

**Comment by breck7** [comment]
ah I see good point. I think we could also generate `admin.js` and the admin css locally, and then a "full bake" would push those to the staging admin server and the netlify to netlify from local?

**Pull request merged**
