### PR TITLE
feat(exp toggle): add teaser

### PR DESCRIPTION
**Pull request by mlbrgl**
- see [slack](https://owid.slack.com/archives/C04L4BHSFSB/p1687537919389129)
- preview: http://staging-site-datapages/admin/grapher/banana-production

### CODE REVIEW

**Comment by mlbrgl** [comment]
Current dependencies on/for this PR:
* master
  * **PR #2356** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2356" target="_blank">Graphite</a> 
    * **PR #2359** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2359" target="_blank">Graphite</a> 
      * **PR #2365** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2365" target="_blank">Graphite</a>  👈
        * **PR #2360** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2360" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2365?utm_source=stack-comment).

**Comment by mlbrgl** [comment]
Current dependencies on/for this PR:
* master
  * **PR #2356** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2356" target="_blank">Graphite</a> 
    * **PR #2359** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2359" target="_blank">Graphite</a> 
      * **PR #2365** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2365" target="_blank">Graphite</a>  👈
        * **PR #2360** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2360" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2365?utm_source=stack-comment).

**Review by ikesau — APPROVED** [review]
Tested on Chrome, Safari and Firefox ✅

**Comment by mlbrgl** [comment]
@mlbrgl started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2365).

**Comment by mlbrgl** [comment]
@mlbrgl merged this pull request with [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2365).

**Pull request merged**
