### PR TITLE
chore(regions): update regions

### PR DESCRIPTION
**Pull request by marcelgerber**
Goes together with https://github.com/owid/cloudflare-workers/pull/19.

Did this using `node itsJustJavascript/devTools/regionsUpdater/update.js`.
This adds some historical countries, and also the `(WHO)` regions.

### CODE REVIEW

**Comment by danyx23** [comment]
I get that the WHO regions can be useful but are these historic regions coming in on purpose or is this an artefact? I'm not super opposed to them but I think we worked quite a bit over the last two years to have a bit of a more understandable regions set and I'm a bit surprised that we are now adding these rather random entities back in.

**Comment by marcelgerber** [comment]
I agree overall.
I suppose we have decided to just use whatever is in ETL, and in there, these entities have been added. I don't know the exact reasons why these have been added, and I agree that we don't necessarily need them. But that is, in a way, a decision of the data managers that we can talk about to them.

In actuality, we already have some of these historical entities in our current set of regions. "Netherlands Antilles" is an example: https://github.com/owid/owid-grapher/blob/6f15e0500783a13f21a473e2eddae588f41ae497/packages/%40ourworldindata/utils/src/regions.json#L56-L64

**Comment by marcelgerber** [comment]
On the other hand, we could also totally opt to maintain a list of "ignored" entities (either here or [in the grapher/regions/latest ETL step](https://github.com/owid/etl/blob/f2380ff06e42676f8e33a42f6f0eafbfb5761237/etl/steps/data/grapher/regions/latest/regions.py)), and to filter out some of these historical entities there.
On the other hand, it could actually also prove useful if our tables were split into `Countries / Historical countries / Aggregates / Other`?

**Comment by marcelgerber** [comment]
I just checked to see that historical countries are always unlisted, i.e. they don't generate a country profile.

**Pull request merged**
