### PR TITLE
Remove a few any in admin client and client utils

### PR DESCRIPTION
**Pull request by danyx23**
This PR removes a few any annotations from adminClient and client utils 

There is one section in clientUtils/util.s that is currently commented out where I would like some input - it used to be that SVGElement was redefined to any in this file, thus disabling all type checks on this type. If I treat the element as used as an Element then I can't access any of the properties in the commented out code. Should there be a runtime type check and if so we do this? I am unclear why asking the SVGElement for a single point would be desirable in the first place...

### CODE REVIEW

**Comment by MarcelGerber** [comment]
What's the state of this? Has this been reviewed, is it ready to be merged?

**Comment by danyx23** [comment]
@MarcelGerber yes I think this could be merged but I don't know if @danielgavrilov did a full PR review or just looked at the one location I was having issues with. Do you want to give it a brief look and then I'll merge it if you ok it?

**Comment by danyx23** [comment]
I just rebased to master to bring it up to date (no other changes though)

**Comment by MarcelGerber** [comment]
Some change in here causes `hoverNearbyFeature` of map charts to not work correctly, and I don't know why:

image

https://github.com/owid/owid-grapher/blob/9544a173a6ad3aff26a9a1daf169c956f3f66a18/grapher/mapCharts/MapChart.tsx#L787-L815

**Comment by MarcelGerber** [comment]
Now fixed!

**Comment by danyx23** [comment]
Thanks a lot @MarcelGerber !

**Pull request merged**
