### PR TITLE
move country standardizer tool to js

### PR DESCRIPTION
**Pull request by sherinkurian**
hi Jaiden,

As requested in https://github.com/owid/owid-grapher/issues/63

screenshot 2018-06-25 07 15 40

Note:

1. Use fuzzysort to determine string similarity
2. Custom selections from dropdown are saved back only when selected input format is the "Non standard country name" and output format is the OWID name (same as the current tool)
3. The country-update tool and instruction pages need to be moved over as well

### CODE REVIEW

**Comment by mispy** [comment]
Woah, this looks great! Pretty much exactly what we were after, in terms of the design and architecture.

Here's a mysqldump of the country name tables: [owid-grapher-country-name-tool.sql.zip](https://github.com/owid/owid-grapher/files/2136740/owid-grapher-country-name-tool.sql.zip)

We can port the update and instructions separately yep

By the way, if you were interested in either of these jobs we'd be very happy if you applied: https://ourworldindata.org/why-you-should-come-do-programming-at-oxford But otherwise your assistance is much appreciated :)

**Comment by sherinkurian** [comment]
Thank you @mispy :)

I believe this PR seems to be in a good place. Looking forward to any feedback.

**Comment by mispy** [comment]
Thanks Sherin, looks really good! Could you test it with this file to verify the behavior against the old version? 
[rugged_data.csv.zip](https://github.com/owid/owid-grapher/files/2178794/rugged_data.csv.zip) Then we should be able to merge :)

You might've seen already, but I also uploaded some more complete database exports so you can check out how the code works for all of our charts https://github.com/owid/owid-grapher#database-setup

**Comment by sherinkurian** [comment]
Thank you for the input file! It caught some wrong assumptions in my code (not converting to ASCII and being case sensitive while matching). PR is ready to merge if there are no concerns with below:

1. One small difference between the old and new tool is in the output CSV column headers. I am using the more verbose readable name (eg: `Our World In Data Name`) in the header instead of `owid_name`. Calling it out in case there is a good reason for it to be this way.

Eg: output with current/python tool
```
Country,owid_name,Year,Terrain Ruggedness Index 100m (Nunn and Puga 2012)
Aruba,Aruba,1996,0.462
Afghanistan,Afghanistan,1996,2.518
```

Eg: output with new tool
```
Country,Our World In Data Name,Year,Terrain Ruggedness Index 100m (Nunn and Puga 2012)
Aruba,Aruba,1996,0.462
Afghanistan,Afghanistan,1996,2.518
```

2. Final thing to note is that this tool is accessible from a different link (shown below) to be safe but happy to replace the currently used link with this one.

screenshot 2018-07-11 08 41 39



Thanks a ton for providing more data for charts. Looking forward to using them for tests :)

**Comment by mispy** [comment]
🎉 Thanks Sherin!! We'll test it out for a bit and then replace the old Python one and look into creating a public version based on this :)

**Pull request merged**
