### PR TITLE
Very early rough draft of reorganizing the owid-grapher project into 8 modular products

### PR DESCRIPTION
**Pull request by breck7**
I am struggling a bit with generalizing dates and so looking for ways to refactor things so that this would be an easy problem. I'm thinking more modularity would be very helpful in making that change an easy one. In this branch I wanted to start the conservation about moving to a strongly opinionated modular design across our repo.

Here is what the folder structure looks like: https://github.com/owid/owid-grapher/tree/arch

There would be a README for each product level folder.

By my count owid-grapher is approximately 8 separate deliverables (I'll call them "products"). I know there is currently some separation going on, I propose we double down and strengthen that. Here's how I separated things in this branch:

- owidCharts
- owidChartMaker (the https://owid.cloud/admin/charts/2782/edit web app. would import "owidCharts")
- owidDb (the db and migration code, perhaps a future data api)
- owidCurator ("owid-admin" pages like https://owid.cloud/admin/variables. would import owidDb and owidChartMaker)
- owidSite (view like ChartPage, Explore Page, Search, header/footer)
- owidSiteBaker
- owidWordPress (https://owid.cloud/wp/wp-admin/)
- owidUtils (catch all for minor classes shared across products)

I think we should keep them in a monorepo but move them into separate folders and try to minimize the touch points as much as possible (within reason). 

Ideally these things would be very loosely coupled and the interfaces would be coded as if we were shipping each as a standalone product. It would be nice to develop/use "owidCharts" with other data sources, or edit owidDb without worrying about how it would affect owidCharts, etc.

I think this could be done in a week, though I could be wrong.

Questions for discussion: Have there been attempts like this in the past? Am I overestimating the benefits? Am I underestimating how much work this would be? Would you draw the product boundaries differently?

### CODE REVIEW

**Comment by danielgavrilov** [comment]
I'm definitely in favour of going in this direction!

And the products you listed are also spot on. In terms of priority, owidCharts is likely the most beneficial to decouple right now – both for us and for others who want to use our Grapher.

For the decoupling of owidChartMaker and owidCurator I'm not so sure – potentially there could be a chartMaker that is more detached from our database and can be used by others externally, but for us the close connection between database concepts/curation and chart-making is quite helpful and maybe not as beneficial to try untangle. 

But given our intent to support arbitrary dimensions and redesign the whole architecture, it's likely these interfaces between components will change drastically and it's not that beneficial to try to define them now. Possibly it's better to invest time architecting the next version, and then finding a path to get us there?

> Have there been attempts like this in the past? 

I haven't attempted it, but Jaiden (who was with us previously) was looking into detaching the chart rendering into a library. It's theoretically easy since we only need 2 JSON files to render a chart – the configuration and the data. The harder part I think was designing an interface that would be usable by external people. Right now that "interface" exists but is basically defined by our database schema.

**Comment by jasoncrawford** [comment]
This is cool. My only suggestion right now would be, let's not do anything right away, but wait until you've had at least a few months of experience with the codebase. And try to find a way to do it incrementally, like maybe pull out one module at a time.

**Comment by mlbrgl** [comment]
I like where this is going! As far as I remember, the reason I created the separate owid-wordpress repo was to tinker more freely with Lando, but now that this is stable, these two should be merged (if only to have a unified deploy process).

**Comment by breck7** [comment]
I'm going to close this PR but keep the branch as a reference and try to get some of these changes in as smaller commits.

**Pull request closed without merging**
