### PR TITLE
chore: remove `postcss` build step

### PR DESCRIPTION
**Pull request by MarcelGerber**
We don't really need it any more; we don't use any cutting-edge CSS and vendor prefixes are mostly a thing of the past.
And IE11 is as good as dead, too.

### CODE REVIEW

**Comment by MarcelGerber** [comment]
This is now live at _tufte_, if you want to have a look. You shouldn't see any differences, though ;)

**Comment by danielgavrilov** [comment]
@mlbrgl Just pinging you if in any case you're relying on PostCSS for any "cutting edge CSS" :) 

This PR is otherwise good to go!

**Review by danielgavrilov — APPROVED** [review]

**Comment by mlbrgl** [comment]
Not that I know :) I'm combing through the diff on the CSS files to check for any potential issues. Will report here if anything shows up.

**Comment by mlbrgl** [comment]
- 🟠 missing @ charset "UTF-8": we would only need it for the down arrow in the mini-toc in h2's but given this is superseded by the `charset` attribute of the `Content-Type:` HTTP header, it's not necessary or used right now. We could add it for extra safety in case the header value changes, but that seems overkill.

- 🟠 unnecessary prefixes in scss and removed by postcss. These are now showing (where they were manually added):
	- flex-flow, box-shadow, border-radius, ::selection, user-select, transform, transform-origin, box-sizing, animation, @ keyframes, filter,

- 🟢 prefixes that weren't in scss and added by postcss. These have been deleted:
	- ::placeholder, user-select, text-decoration-color
	
Removing postcss is a zero-sum operation in terms of KB transferred to the client: we're adding 1KB of styles in owid.css(from fontawesome mainly), and we're removing about 1KB in commons.css (mostly from ::placeholder).
On the plus side, this simplifies the build process, which makes me lean towards merging.

**Pull request merged**
