### PR TITLE
datapages design QA

### PR DESCRIPTION
**Pull request by mlbrgl**
This PR contains minor - mostly visual - changes surfaced by the design QA. 

See the following threads for the exhaustive list of changes applied:
- https://owid.slack.com/archives/C04L4BHSFSB/p1686214859287869
- https://owid.slack.com/archives/C04L4BHSFSB/p1686241110227159

### CODE REVIEW

**Comment by mlbrgl** [comment]
Current dependencies on/for this PR:
* master
  * **PR #2218** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2218" target="_blank">Graphite</a> 
    * **PR #2233** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2233" target="_blank">Graphite</a> 
      * **PR #2248** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2248" target="_blank">Graphite</a> 
        * **PR #2250** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2250" target="_blank">Graphite</a> 
          * **PR #2259** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2259" target="_blank">Graphite</a> 
            * **PR #2270** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2270" target="_blank">Graphite</a> 
              * **PR #2283** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2283" target="_blank">Graphite</a> 
                * **PR #2286** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2286" target="_blank">Graphite</a> 
                  * **PR #2303** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2303" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2303?utm_source=stack-comment).

**Review by ikesau — APPROVED** [review]
Went through the slack threads and verified the things with `:soon-tick:` 👍

**Comment by mlbrgl** [comment]
@mlbrgl started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2303).

**Comment by mlbrgl** [comment]
@mlbrgl merged this pull request with [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2303).

**Pull request merged**
