### PR TITLE
fix(admin): AdminIndexPage displays correct chart type for line charts

### PR DESCRIPTION
**Pull request by MarcelGerber**
This is not really a regression on `next` but is already to be seen on live: On the admin landing page, some line charts display a type of "Unknown" in the type column.
This happens because `Grapher.tsx` strips off all default values, and the default value for the chart type is `LineChart`. Therefore the `charts.json` response includes `type: null` for those charts.

If there's a better way to fix this please let me know :)

image

### CODE REVIEW

**Comment by breck7** [comment]
Might be better to do it at the view layer?

**Comment by MarcelGerber** [comment]
Hm, my thought there is that any other script (or human) consuming `charts.json` might then run into the same problem, that some charts don't have a chart type for no obvious reason.

I don't think there's anything else that consumes `charts.json` at the moment, but there certainly might be something in the future.

**Comment by breck7** [comment]
What about getting rid of the any? `(chart: any)` to `(grapher: GrapherInterface)`

The Interface is `type?: ChartTypeName`, so the code that consumes it should handle the undefined case.

In general I've personally found a good rule of thumb is to never serialize defaults.

```
const serialized = {}
assert(new SomeClassThatMayHaveSomeDefaults(serialized).serialize() === serialized)
```

There's probably a name for this pattern (or maybe I'm wrong and it's an anti-pattern after all).

**Comment by MarcelGerber** [comment]
Okay, I now went with that way. I still think it's confusing to see an API response with `type: null` to then realise that's the default value, but still went with it.

I also struggled a bit at how to express the type - [it's only a subset of `GrapherInterface` and also contains some other properties](https://github.com/owid/owid-grapher/blob/b9ac880496cb6caf86738654a2de5e180f8a2590/db/model/Chart.ts#L131-L148) - and went with the more verbose, but explicit way to reference all `GrapherInterface` types explicitly.
(I know I could've also went with `Pick<GrapherInterface, ...>`, but that's more confusing in my mind, with this many properties)

**Comment by breck7** [comment]
This LGTM. I feel like we just have more root level cleanup to do of the adminSite later on.

**Pull request merged**
