### PR TITLE
Fixed separator lines gap issue.

### PR DESCRIPTION
**Pull request by parthiv360**
Solved this following issue by making minimal changes in the DataTable.scss. 
Issue No. #2767

### CODE REVIEW

**Review by sophiamersmann — CHANGES_REQUESTED** [review]
Hey @parthiv360

Thank you for your contribution!

Updating the CSS selector is a valid strategy and works in many cases.

In a few instances though, it's not quite what we want. If you look at the [example chart](https://ourworldindata.org/grapher/maddison-data-gdp-per-capita-in-2011us-slopechart?tab=table) and scroll to the very bottom, you'll see that some separator lines are still missing while in other places, separator lines are now duplicated.

Screenshot 2023-10-24 at 07 27 54

The underlying issue here is that empty cell values are not being assigned the correct dimension classes:

Screenshot 2023-10-24 at 07 39 31

This is the function that renders data cells: https://github.com/owid/owid-grapher/blob/91ad2fcdaa2e5ed6bea54184e83d1827e47850c3/packages/%40ourworldindata/grapher/src/dataTable/DataTable.tsx#L400

Add dimension classes (`dimension-${column.key}`) to empty cells should solve the issue.

**Comment by parthiv360** [comment]
Hey @sophiamersmann I did the changes as you asked for. Please review it. Thank you

**Review by sophiamersmann — CHANGES_REQUESTED** [review]
Thank you!

There is one more line that renders empty cells and needs the appropriate dimension classes: https://github.com/owid/owid-grapher/blob/522291804caa284fdc2aaeb994d5b4a3c76ccdf5/packages/%40ourworldindata/grapher/src/dataTable/DataTable.tsx#L416

**Comment by parthiv360** [comment]
Hey @sophiamersmann I made the required changes. Thank you for helping.

**Comment by parthiv360** [comment]
Hey @sophiamersmann do I need to make any more changes on this issue?

**Comment by sophiamersmann** [comment]
Looks good! Thank you for your contribution!

**Pull request merged**
