### PR TITLE
Use `readonly` in many places to enforce immutability

### PR DESCRIPTION
**Pull request by danielgavrilov**
Prompted by https://github.com/owid/owid-grapher/pull/856, I thought I would try out what happens if we turn every array to be `readonly`. 

As I said there:

> Every `@computed` getter returning an object or an array is prone to this type of errors right? Because it's memoized, any changes are persisted when it's retrieved again.
> 
> I wonder if we should (strive to, from now on) use types `Readonly` and `ReadonlyArray` in these computeds so that TypeScript prevents these problems?

I didn't run into any more bugs like in #856 in this PR so far, but I only went through parts of LineChart and ScatterPlot so far.

To me it seems like a good idea to default to `readonly` unless we need a mutable array, but we would need to write a whole lot of `readonly`s to do that. What do you think?

### CODE REVIEW

**Comment by MarcelGerber** [comment]
> I didn't run into any more bugs like in #856 in this PR so far, but I only went through parts of LineChart and ScatterPlot so far.

Yeah, at least for uses of `.reverse()` I did a (loose) search through our codebase already, and didn't find anything else other than the `ColorScheme` code in #856. The only other method that modifies the array in place and that I can think of right now would be `.sort()`, which we especially use through `sortNumeric`.


> To me it seems like a good idea to default to `readonly` unless we need a mutable array, but we would need to write a whole lot of `readonly`s to do that. What do you think?

Yes, makes sense to me.
It would be great if we could default our arrays to default to readonly, and only set them mutable when we want it, but I guess that's not possible with TS.

**Comment by danielgavrilov** [comment]
I used a regex (`[a-zA-Z0-9]+:\s+[a-zA-Z0-9]+\[\]`) to try find all the easy places where we can easily add `readonly`. There are definitely still places where we use type inference and a mutable array is inferred.

The goal really is to normalize the use of `readonly` and `Readonly<T>`. It's quite hard to rewrite everything to use it. 

I found it really helpful to have `readonly` on `${X}Manager` interfaces because it makes it clear what properties are mutable for the manager. 

As you say Marcel: ideally everything should be `readonly` by default and the modifier should be `mutable`. Looking forward to the day that's possible.

**Review by MarcelGerber — APPROVED** [review]
LGTM. I haven't looked through everything, of course, but from what I looked at this all makes sense.
I guess we should get this PR in quickly to avoid nasty merge conflicts.

The only thing I'm not sure about is the re-definition of the `ckmeans` type - would it not be easier to just `.slice()` the input into ckmeans (i.e. `ckmeans(arr.slice())`)?


---
As for a `mutable` TS type, I guess that would be this then: https://github.com/microsoft/TypeScript/issues/24509. But doesn't look like it'll be coming anytime soon :(

**Comment by danielgavrilov** [comment]
> The only thing I'm not sure about is the re-definition of the `ckmeans` type - would it not be easier to just `.slice()` the input into ckmeans (i.e. `ckmeans(arr.slice())`)?

It's just a performance optimization, didn't want to add processing time on the map by copying the `values` array. Though it's probably an insignificant overhead to use `.slice()`. Will revert.

**Comment by danielgavrilov** [comment]
There are two reasons I'm a bit hesitant on this PR:
- 3rd party libraries not having the (strictly) correct `readonly` types
- sometimes (especially in tests) immutable objects/interfaces get in the way – you know what you are doing, so you don't want immutability getting in the way leading to [this](https://github.com/owid/owid-grapher/pull/857/files#diff-bcbda5c8f35b53bc35e67a52dd8f57c4b813857a263d8783df5be11603114bafL401-R413)

**Comment by danielgavrilov** [comment]
Closing because of issues mentioned above, and we have other PRs adding type annotations which are a better first step.

**Pull request closed without merging**
