### PR TITLE
🎉 update scrollY when collapsing expandable-parapraph

### PR DESCRIPTION
**Pull request by ikesau**
Another little QOL thing asked for by Marwa

https://github.com/owid/owid-grapher/assets/11844404/62bb6f39-8827-43e6-ad7d-0941610cc7a8

### CODE REVIEW

**Review by mlbrgl — APPROVED** [review]
I can't quite pinpoint it but I'm somehow not convinced by the asymmetry of the open / close behaviour. It's less confusing than before though, especially with longer texts.

**Comment by ikesau** [comment]
@mlbrgl I think you're right - refactored it to animate instead.

Tested on Safari/Chrome/Firefox

https://github.com/owid/owid-grapher/assets/11844404/04a35b1a-9d58-47b4-b295-99fe3c1ccbf9

**Comment by mlbrgl** [comment]
@ikesau nice! I think that's clearer now 👍

I just noticed that the margin with the text got reduced [here](http://staging-site-expandable-paragraph-location/poverty) and feels a bit too close (right is live): 
Screenshot 2023-06-22 at 18 29 47

**Comment by ikesau** [comment]
Hmm yeah that's not up to date. Is the CSS cached somehow?

**Pull request merged**
