### PR TITLE
Update MathJax to version 3

### PR DESCRIPTION
**Pull request by MarcelGerber**
MathJax was updated to version 3 last year, with some major changes: http://docs.mathjax.org/en/v3.0-latest/upgrading/whats-new-3.0.html

I think TypeScript support, more robust server-side usage (which is the only way we use mathjax) and improved speed are things we could use.

That's why I updated to `MathJax@3.0.1` and updated the corresponding code.
Our usage is quite similar to this example: https://github.com/mathjax/MathJax-demos-node/blob/master/direct/tex2svg

### CODE REVIEW

**Comment by MarcelGerber** [comment]
We could also switch to the `HTML+CSS (CommonHTML)` output format of MathJax, which uses HTML and a webfont and is now their preferred one.
The main reason why I didn't switch is because it generates an inline style that has to be included in the page, and that makes it even harder for me to test this (since I don't have access to any blog posts and cannot simply run `yarn bake`).

**Comment by MarcelGerber** [comment]
Btw, there's a nice search for the 9 pages that currently use Latex formulas, and which would need to be checked after this lands: https://github.com/owid/owid-static/search?q=MathJax-SVG-1-Title

**Comment by danielgavrilov** [comment]
Thank you very much for this @MarcelGerber – especially helpful as I attempted and failed to get it working in the past.

Right now things are a bit crazy while we try to cover the Coronavirus. I will hopefully have time to review this in a week or so!

**Comment by MarcelGerber** [comment]
Yeah, no problem.
Keep up the great work, your reporting on Covid is very valuable and helpful!

**Comment by danielgavrilov** [comment]
Hey @MarcelGerber, thanks a lot, really well done on this! Not sure how you managed to figure this one out without access to WordPress.

I made small changes to the CSS to match the previous behaviour (see #363). 

Also gave you push access so it's easier to collaborate. Will close this PR in favour of #363 – feel free to push changes there!

**Comment by MarcelGerber** [comment]
> Not sure how you managed to figure this one out without access to WordPress.

Yeah, it was a bit tricky. I basically simulated some text that might look like blog content, with `[latex]` tags inside it.

> Also gave you push access so it's easier to collaborate. Will close this PR in favour of #363 – feel free to push changes there!

Thank you! I will have a look :)

**Pull request closed without merging**
