### PR TITLE
✨ (donate) add faqs

### PR DESCRIPTION
**Pull request by mlbrgl**
- [staging](http://staging-site-donation-faqs/donate)
- [figma](https://www.figma.com/file/y3LP6wEnwyXFH6x4CpkxN5/%5BProject%5D-Donation-Flow?type=design&node-id=158-2319&mode=design&t=mnCTzy0Wky40U3pi-0) 

Screenshot 2023-11-07 at 17 44 03

- content is coming from a [config gdoc](https://docs.google.com/document/d/194PNSFjgSlt9Zm5xYuDOF0l_GLKZbVxH2co3zCok_cE/edit)
- not hydrated at the moment, only SSR. Will address hydration when me move towards the [accordion-based version](https://www.figma.com/file/9bQW46okOjxeJtismQQdPu/%5BDesktop%5D-Screens-1.0?type=design&node-id=5301-1464&mode=design&t=XghngjE4sWhwI8ll-0)

### CODE REVIEW

**Comment by mlbrgl** [comment]
Current dependencies on/for this PR:
* master
  * **PR #2888** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2888" target="_blank">Graphite</a> 
    * **PR #2889** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2889" target="_blank">Graphite</a> 
      * **PR #2903** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2903" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2903?utm_source=stack-comment).

**Review by ikesau — APPROVED** [review]
Looks good!

Can you please put the Gdoc in the shared drive? (Maybe in its own folder like the Homepage one)

In that Gdoc, "funded in our Annual Report" links to http://staging-site-donation-form/uploads/2022/10/Annual-Report-2021-1.pdf

**Comment by mlbrgl** [comment]
thanks! Done and done.

**Comment by mlbrgl** [comment]
Thanks! 

> Can you please put the Gdoc in the shared drive? (Maybe in its own folder like the Homepage one)

✅

> In that Gdoc, "funded in our Annual Report" links to http://staging-site-donation-form/uploads/2022/10/Annual-Report-2021-1.pdf

✅

**Comment by mlbrgl** [comment]
### Merge activity

* **Nov 9, 3:32 AM**: @mlbrgl started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2903).

**Pull request merged**
