### PR TITLE
fix(datapages): don't bind charts in the all charts block to the window

### PR DESCRIPTION
**Pull request by marcelgerber**
basically re-applying 7eb70960b82411cdd23670adbe04139875cf4646 (#2466)

### CODE REVIEW

**Comment by danyx23** [comment]
Current dependencies on/for this PR:
* master
  * **PR #2879** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2879?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #2848** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2848?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #2880** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2880?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #2739** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2739?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #2853** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2853?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #2877** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2877?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #2886** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2886?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
              * **PR #2914** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2914?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #2918** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2918?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                  * **PR #2920** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2920?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                    * **PR #2922** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2922?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                      * **PR #2929** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2929?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                        * **PR #2927** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2927?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                        * **PR #2921** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2921?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2921?utm_source=stack-comment).

**Review by danyx23 — APPROVED** [review]
Great, thanks! I've rebased your changes onto the current version of the PR chain so that Sophia can easily release them all together when the time comes.

**Comment by larsyencken** [comment]
@sophiamersmann Also assigning this one your way now that Marcel's out. Update, merge or close it as you see fit once the other work is out.

**Comment by danyx23** [comment]
### Merge activity

* **Nov 27, 6:24 AM**: @danyx23 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2921).

**Pull request merged**
