### PR TITLE
:sparkles: add column githubUsername to users table

### PR DESCRIPTION
**Pull request by Marigold**
- Add column `users.githubUsername`
- Match detected Tailscale user on githubUsername rather than fullName
- Add people with GitHub names different from their full names

## TODO after merging:
- [ ] Pull owid-grapher on all staging servers and run `make migrate`

### CODE REVIEW

**Review by marcelgerber — COMMENTED** [review]
Hi! This makes sense to me, but I'm wondering why we're not just going all the way directly, and identifying all users by GH username always?

**Comment by Marigold** [comment]
@marcelgerber sorry, what do you mean by that? (If your idea is out of scope, can we still merge this? It's needed for a fix with [editing users](https://github.com/owid/etl/pull/3521) in ETL)

**Comment by marcelgerber** [comment]
Sorry, I should've been more clear.

Currently, we're still using GH's display name as the identifying feature, e.g. "Mojmir Vinkler". However, with this PR, we are sometimes falling back to GH usernames (e.g. "Marigold"), namely when such a display name is not set, or is not equal to the full name.

Would it not make sense to instead always use the GH username (e.g. "Marigold") instead?

Looking at the output of `tailscale status --json`, we do have that one available:
```json
     "40781454737177829": {
       "ID": 40781454737177829,
       "LoginName": "Marigold@github",
       "DisplayName": "Mojmir Vinkler",
       "ProfilePicURL": "https://avatars.githubusercontent.com/u/1550888?v=4",
       "Roles": []
     },
```

If you don't want to change that, then feel free to merge it as-is. It's not too hard to change it in the future, too :)

**Review by marcelgerber — APPROVED** [review]
Nice, looks good now!

**Pull request merged**
