### PR TITLE
🎉 (slope) support facetting / TAS-734

### PR DESCRIPTION
**Pull request by sophiamersmann**
Adds facetting support for slope charts.

If there are many facets it could be nice to declutter them, but I don't have time for that now.

### CODE REVIEW

**Comment by sophiamersmann** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/4247?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4247** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/4247?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/4247?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#4222** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/4222?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#4207](https://github.com/owid/owid-grapher/pull/4207) <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/4207?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#4205** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/4205?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4192** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/4192?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4170** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/4170?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4159** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/4159?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by marcelgerber** [comment]
There's a weird thing going on where on http://staging-site-slope-charts/grapher/antibiotic-usage-by-surveillance-category?tab=slope&time=2020..2022, the line connectors are only shown when Uganda is removed - even though the chart size itself is the same no matter what:

CleanShot 2024-12-09 at 18 15 00
CleanShot 2024-12-09 at 18 15 59

**Review by marcelgerber — APPROVED** [review]
Looks good, except for the bug I just commented about 🙌

No worries if you can't address that bug - it's not a dealbreaker!

**Comment by sophiamersmann** [comment]
This happened because slope charts without data used a default domain extent of [-1, 1]. I pushed a fix!

**Comment by sophiamersmann** [comment]
### Merge activity

* **Dec 11, 7:47 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/4247).

**Pull request merged**
