### PR TITLE
Fix remote test option for deploy script

### PR DESCRIPTION
**Pull request by mlbrgl**
pretty-quick requires a VCS to run, which is (was) not copied over to the tmp rsync target for remote tests. 

This fix is not great, as it adds yet another 80MB (current size of .git) to each staging server, and in some circumstances might cancel out the time gained from using pretty-quick. The alternative is to add a custom ~`typecheck`~ `testcheck` variant, e.g. `yarn prettify:check-no-vcs && yarn typecheck && yarn test`, either to package.json or directly hardcoded in deploy.sh. Both options create an alternate path for tests, a door I'd rather leave closed if not necessary.
If space becomes an issue, this can be re-evaluated.

This PR also moves some dependencies to devDependencies.

### CODE REVIEW

**Comment by breck7** [comment]
Ah! I didn't consider that code path. PrettyQuick does require the master branch to compare against.

I definitely don't think we want to rsync .git over.

What about if added a oneliner: 
```
if [ "$2" == "-r" ]; then
  yarn prettify:check # Run pretty-quick locally to avoid having to copy .git to server
  # Run pre-deploy checks remotely
  $RSYNC_TESTS $DIR/ $HOST:$SYNC_TARGET_TESTS

  ssh -t $HOST 'bash -e -s' <<EOF
  cd $SYNC_TARGET_TESTS
  yarn install --production=false --frozen-lockfile
  yarn typecheck && yarn test
EOF
```
So pretty-quick is always run locally (only takes 1s, so shouldn't be bad).

**Comment by mlbrgl** [comment]
No worries. Yep that would work, thanks! I was trying to keep `yarn testcheck` as the "one-stop shop" for all tests, thus avoiding having to remember updating `deploy.sh` when and if `testcheck` gets updated.

Here are the limitations of copying git over I had in mind:
- space usage
- longer rsync overrides when syncing to the same location (most of the time, this would only happen when deploying to production) - something I wanted to confirm
- granted, this is not the most elegant approach

Anything else on your end @breck7?

**Comment by MarcelGerber** [comment]
I'm also not keen on syncing the git folder.

Problems I see there include:
- I'm pretty sure the contents of the .git folder can differ a lot between us devs, and there is quite a discrepancy between the files in there for each of us
- It's also just a lot of files. Without knowing exactly how `rsync` works, it would need to compare the contents of many, many files when deploying, and also uploading and deleting many along the way.
- Also, it seems like `rsync` decides whether to update a file only on the modification date (unless we're using some other mode?). That in itself can lead to problems inside the git folder, and I don't know how gracefully git can handle inconsistencies in there. Would be bad either way, though, to have some state on the live server where a branch HEAD is wrong or something like that.

In my "Switch to GitHub Actions" PR (currently open) I also ran into issues with `pretty-quick`, and solved that by introducing a `yarn testcheck:ci` script that runs prettier instead. Maybe we can go the same route here? (Prettier isn't _that_ slow)

**Comment by mlbrgl** [comment]
@MarcelGerber thanks for your feedback. Looking into your PR #569 gave me an idea, how about hooking up `testcheck` to something like this:
```
#!/bin/bash

# Run pretty-quick in git working directories (e.g. dev) and prettier in others (e.g. CI)
if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  yarn prettify:check && yarn typecheck && yarn test
else
  yarn prettify-all:check && yarn typecheck && yarn test
fi
```

We can then run `yarn testcheck` in both environments and hide away this specificity?

**Comment by MarcelGerber** [comment]
Hm, I'm not quite sure that's actually better.
Yes, we would have to keep both code paths in sync when making changes, but that's the same for your solution.
And we can just choose for each use case which one is better: `pretty-quick` for dev, `prettier` for CI (Travis / GH Actions), `prettier` for deploy.
Maybe we can come up with a better name than `testcheck:ci`, yes, but I still think that's the way to go. For the name, maybe even go the other way and call the quick one `testcheck:dev` or `testcheck:local`, so the slower variant stays the "normal" one?

But I'm interested what's your opinion there @mlbrgl @breck7, so please feel free to comment what you think.

**Comment by mlbrgl** [comment]
> And we can just choose for each use case which one is better

That's precisely what I'm trying to avoid, exposing an unnecessary choice, because the resulting decision is going to be systematically the same: pretty-quick for git working copies and prettier for the rest. But I have a feeling I might be missing a use case, which makes you want to expose that dichotomy.

As for the update in multiple places issue, it's easily fixable in the script:
```sh
#!/bin/bash

# Run pretty-quick in git working directories (e.g. dev) and prettier in others (e.g. CI)
if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  PRETTIFY_CMD="yarn prettify:check"
else
  PRETTIFY_CMD="yarn prettify-all:check"
fi

$PRETTIFY_CMD && yarn typecheck && yarn test
```

Anyway, not pushing too hard on this, just curious now what your thoughts are.

**Pull request closed without merging**
