### PR TITLE
enhance: Add view to mysql that exposes the variables used by charts

### PR DESCRIPTION
**Pull request by danyx23**
We had this in datasette and bigquery but now we can also do it as a view with the shiny new mysql 8 json_table function. This might be useful for data update work.

### CODE REVIEW

**Comment by danielgavrilov** [comment]
There is already a `chart_dimensions` table that is used for this purpose?

**Comment by danyx23** [comment]
Ah, right. To be honest I had just missed that this table exists. But looking at it now it seems that the variable used in the map section of the config is not included (and/or maybe there is some other difference?).

Running this query gives a difference between the content of chart_dimensions and this view (copied it as opposed to querying it because I happened to look at it at a branch):
```sql
with v as 
(
SELECT
	id as chartId,
	config ->> '$.map.variableId' as variableId
FROM
	charts
WHERE
	config ->> '$.map.variableId' is not null
UNION DISTINCT
-- and union it together with all the variables hidden in the dimensions json array, extracted with json_table
SELECT
	id as chartId,
	dims.variableId as variableId
FROM
	charts AS c
CROSS JOIN
JSON_TABLE(
  c.config,
	'$.dimensions[*]'
  COLUMNS(
    variableId INT PATH '$.variableId'
  )
) AS dims)
select
	cd.id,
	cd.order,
	cd.property,
	cd.chartId,
	cd.variableId,
	v.chartId as vcid,
	v.variableId as vvid
from
	chart_dimensions cd
right join v on
	cd.chartId = v.chartId
	and cd.variableId = v.variableId
where
	cd.chartId is null
```

I think that since this is probably not a super frequently used query I'm tempted to replace the existing table with the view because it lowers the maintenance burden somewhat (you can't forget to update chart_dimensions in a script e.g. if you modify the json structure). 

What is nice about the chart_dimensions table is the property and order field, I added those to the view as well.

What do you think, should I remove the code that uses chart_dimensions and replace it with the view?

**Comment by danielgavrilov** [comment]
> because it lowers the maintenance burden somewhat

I agree, it would be great to have it as a view. Is there some way to add a foreign-key constraint on the dimensions this way? One of the current uses of `chart_dimensions` is to prevent data being deleted that is used in charts.

**Review by Marigold — APPROVED** [review]
I've leave the decision whether to keep this one or chart_dimensions to you guys. Otherwise looks good, I'd love to have it in staging as soon as possible :)

**Comment by Marigold** [comment]
Ok, I'll switch to `chart_dimensions` until we decide what to do with this.

**Comment by danielgavrilov** [comment]
Seems like we abandoned this and will stay with `chart_dimensions` for now? 

Closing this since it's a bit stale, feel free to reopen if we want to keep it!

**Comment by danyx23** [comment]
Yes that makes sense. I deleted the charts_variables view that was accidentally created on the live db by a migration that should not have been run yet.

**Pull request closed without merging**
