### PR TITLE
Use tsx for scripts and local admin server

### PR DESCRIPTION
**Pull request by rakyi**
This improves the DX significantly when running admin locally. Admin server restarts faster and client hot reload doesn't end in a network error. TS errors don't block running the code.

We can also run many scripts locally with the TS source directly instead of using the compiled output from `itsJustJavascript`. The remaining reasons to keep using it for some cases are:

* `tsx` doesn't work with Jest OOTB, our best bet is probably to switch to Vitest
* Compiling the code separately before running it in prod is safer and should be more performant, especially for long-running processes

### CODE REVIEW

**Review by marcelgerber — APPROVED** [review]
Nice, this works really well and makes the dev experience lots better!

The only difference in behaviour I could make out is that, after an uncaught exception, the dev admin server doesn't automatically restart. Try going to http://localhost:3030/admin/charts/0/edit, for example, which will throw an exception and make the admin server crash.

I think it's fine to acknowledge this difference in behaviour for now (as it is also the way I found out that this exception is actually uncaught), and to let devs know that by hitting "Enter" in the tsx process, they can restart the process.
And if it becomes too annoying at some point, we can still consider how else we can solve this.

**Comment by rakyi** [comment]
I'm not sure what is causing the difference in behavior, since `tsx` is claiming to behave the ~same as `node`. But I'm surprised the server restarts/recovers with your example error in master, since we are clearly not handling the errors and the server should crash in that case too.

When I tried [handling the error properly](https://expressjs.com/en/guide/error-handling.html), we get 404 in the browser instead of unhandled 500 and the server doesn't crash with `tsx`.

The proper solution then seems to be to handle the errors correctly. Do you know why we currently don't?

**Comment by rakyi** [comment]
Rebased on master.

**Comment by rakyi** [comment]
After discussing with Daniel, we decided I'll add the missing error handling to async functions.

**Comment by marcelgerber** [comment]
> I'm not sure what is causing the difference in behavior, since `tsx` is claiming to behave the ~same as `node`. But I'm surprised the server restarts/recovers with your example error in master, since we are clearly not handling the errors and the server should crash in that case too.

I guess it's because we were using `tsc-watch` - in particular, `yarn run tsc-watch -b --onSuccess "yarn startAdminServer"` in this case.
While their docs don't say anything about restarting after a crash, I guess that's what they are doing.

**Pull request merged**
