### PR TITLE
fix: strip out newlines in TextWrap

### PR DESCRIPTION
**Pull request by marcelgerber**
Issue: [Lucas reported this issue here on Slack](https://owid.slack.com/archives/C46U9LXRR/p1653160820675989)

In our svg and png exports, the first line after a newline had an unintentional indent:

This happened because `TextWrap.lines()` was not stripping out leading newlines, and they would be rendered as a space in the svg version of a chart (but not in the HTML version).
E.g. for the above chart, it would be `["- Flexitarian [...]", "\n- Pescetarian [...]"]`.

I also used the opportunity to add test cases for `.lines()`, which didn't have any test coverage beforehand.

### CODE REVIEW

**Comment by danielgavrilov** [comment]
I added a (failing) test for multiple newlines not having correct height ([chart](http://localhost:3030/grapher/butterfly-trends-netherlands)):

Screenshot 2022-05-23 at 09 18 50

I am not sure what a good fix might be here. We could just leave a space `" "` in order to get non-zero height for the line in between, but feels hacky?

**Comment by marcelgerber** [comment]
Very good find!
One fix is to have `Bounds.forText` return `{x, y, height}` as usual even for empty strings.

I know we use `Bounds.forText` in many cases, but I hope we're not relying on its empty-string behaviour all too much 🤞🏻 
And if we do, then I would hope that the SVG tester will showcase this for us, at least. ⌛

**Comment by danielgavrilov** [comment]
Ah! I was thinking we can't do that, because: https://github.com/owid/owid-grapher/blob/9db93a648d769e020a4b600dc885be53c7308a20/grapher/text/TextWrap.test.ts#L61-L64

But`TextWrap` takes care of that case instead: https://github.com/owid/owid-grapher/blob/31fc73b21799963e97f908b72b601a85f39979aa/grapher/text/TextWrap.tsx#L133

Sounds good to me to handle it like this. If the string is empty, it shouldn't be `Bounds` responsibility to decide it should be zero width.

**Review by danielgavrilov — APPROVED** [review]

**Comment by marcelgerber** [comment]
Indeed! I also ran the SVG Tester on _just that_ change, and it did _only_ find some cases where the SVG changes because of a trailing space in the subtitle that is now handled differently (https://github.com/owid/owid-grapher-svgs/commit/2e19a6c4f828536011034925fc2d3feb3d23e928).

So we're good to go on all fronts. Thank you for the review and usual thoroughness, daniel!

**Pull request merged**
