### PR TITLE
✨ (static charts) make charts mobile-friendly

### PR DESCRIPTION
**Pull request by sophiamersmann**
Collection of small improvements to make static charts more mobile-friendly. Some changes apply to static+mobile charts only, others apply to all charts (interactive and static).

For all charts:
- Font size changes
    - Rather than micro-managing font sizes for the special case of static+mobile charts, I rely on the `baseFontSize` to scale all font sizes up
    - To make that work, I have adjusted some font sizes to make sure it looks good for all cases (desktop/mobile, interactive/static)
    - I compiled a list of font sizes currently in use [here](https://www.notion.so/owid/d24b12ac2a754420af4aeba26ba21cca?v=647f5989b92d46e0bd802a52597ddcda&pvs=4);  the table also denotes the changes I made
    - The biggest change I made is decreasing the font size of tick labels by a few pixels (0.9 -> 0.75, i.e. 14.4px -> 12px for `baseFontSize` = 16px)
- Updated colours in the chart to use Grapher's dark and light colours
- Updated the opacity used for bars and areas (0.8)
- Draw a white outline around value labels that are rendered into the chart area and might overlap with grid lines (DiscreteBar and StackedDiscreteBar)
- Make the detail's font size respect the base font size
- Make entity labels in ScatterPlots respect the base font size

For static+mobile charts only:
- Increased the thickness of axis lines
- Increased the thickness of lines in LineCharts and SlopeCharts
- Increased the thickness of lines in Maps
- Hide line markers in LineCharts
- Changed the text colour of the subtitle, footer and axis labels
- Remove underlines for links in the footer
- If the footer text is long, decrease its font size
- SlopeChart: Hide the vertical axes on the sides

---

- Mobile optimizations are also applied to thumbnails generated for social media:
    - chart: [old](https://ourworldindata.org/grapher/thumbnail/life-expectancy?imType=og) / [new](http://staging-site-export-charts-for-mobile/grapher/thumbnail/life-expectancy?imType=og)
    - map: [old](https://ourworldindata.org/grapher/thumbnail/burden-of-disease-who?imType=og) / [new](http://staging-site-export-charts-for-mobile/grapher/thumbnail/burden-of-disease-who?imType=og)

### CODE REVIEW

**Comment by sophiamersmann** [comment]
Current dependencies on/for this PR:
* master
  * **PR #2967** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2967?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #2975** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2975?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #2977** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2977?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2977?utm_source=stack-comment).

**Review by ikesau — APPROVED** [review]
pretty wild PR to review! there are so many magic numbers throughout that I feel like a numerologist 😅 

i sampled ~50 random diffs from the tester and looked at ~10 charts on my local at various resolutions (static and dynamic) and couldn't spot any errors.

The code seems good too. I almost suggested adding some comments here and there but after giving it some thought I couldn't imagine comments actually adding clarity.

We might find some issues once this is deployed and we have more eyes on it, but for now I think it's good to go 👍

**Comment by danyx23** [comment]
Hi there! Just came here because I saw the comment about the magic numbers :). What do you think about turning a good bunch of these into shared constants? It wouldn't even need to be semantic names, it could just be stuff like `const BASE_FONT_SIZE_HELPER_11 = 11`. The main advantage would be that it would be much easier in the future to refactor these values because uses could easily be found (grepping for 11 in the codebase is probably not very nice)

**Comment by sophiamersmann** [comment]
Thank you for the quick review, @ikesau :)

Yeah, Grapher is big on magic numbers. I made this [list of font sizes currently in use](https://www.notion.so/owid/d24b12ac2a754420af4aeba26ba21cca?v=647f5989b92d46e0bd802a52597ddcda&pvs=4) and hoped I could unify font sizes to an extent that a refactor made sense, but realised quickly that there is usually a good reason for a slightly smaller/bigger font size than usual, then I gave up on it. Using non-semantic names hadn't occurred to me – I'll try that. But I think I'd prefer to do a possible refactor in a stacked PR, and get this one shipped now.

**Comment by sophiamersmann** [comment]
### Merge activity

* **Jan 9, 10:17 AM**: @sophiamersmann started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2977).

**Comment by sophiamersmann** [comment]
It's a little unhinged, but why not 😅 

```js
export const GRAPHER_FONT_SCALE_9_6 = 9.6 / BASE_FONT_SIZE
export const GRAPHER_FONT_SCALE_10 = 10 / BASE_FONT_SIZE
export const GRAPHER_FONT_SCALE_10_5 = 10.5 / BASE_FONT_SIZE
export const GRAPHER_FONT_SCALE_11 = 11 / BASE_FONT_SIZE
export const GRAPHER_FONT_SCALE_11_2 = 11.2 / BASE_FONT_SIZE
export const GRAPHER_FONT_SCALE_12 = 12 / BASE_FONT_SIZE
export const GRAPHER_FONT_SCALE_12_8 = 12.8 / BASE_FONT_SIZE
export const GRAPHER_FONT_SCALE_13 = 13 / BASE_FONT_SIZE
export const GRAPHER_FONT_SCALE_14 = 14 / BASE_FONT_SIZE
```

Merged in the next PR!

**Comment by danyx23** [comment]
Nice, thanks! :)

**Pull request merged**
