### PR TITLE
fix(gdocs-admin): update gdocs state based on the latest state

### PR DESCRIPTION
**Pull request by marcelgerber**
Fixes the issue that can be seen in https://github.com/owid/owid-grapher/issues/2393#issuecomment-1618532764.

This was happening because the `currentGdoc` variable was still holding the state from _before_ the fetch happened, and so if the slug was updated _while_ the fetch ran it would be reset to what it was before when the fetch finished.

I fixed this by rewriting it to use the ["updater function" version of the `setGdoc` call](https://react.dev/reference/react/useState#updating-state-based-on-the-previous-state).

---

Somewhat relatedly, but not necessarily something we need to address in this PR already: I was thinking that some things would probably be easier if we split the `originalGdoc` and `currentGdoc` states into two? I don't know the exact reason why they're one state right now, but if it's only for atomic updates, then I think React would guarantee these either way?

### CODE REVIEW

**Comment by marcelgerber** [comment]
Current dependencies on/for this PR:
* master
  * **PR #2396** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2396" target="_blank">Graphite</a>  👈
    * **PR #2375** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2375" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2396?utm_source=stack-comment).

**Review by danyx23 — APPROVED** [review]
Looks good, good catch

**Review by ikesau — APPROVED** [review]
LGTM, thanks!

iirc, I united the two gdocs into a single state object due to a race condition that was occurring back when we had an autosave effect.

I don't think it's necessary anymore, so feel free to separate them again if you think it would make things easier to reason about. I guess we'd still need proxy functions to keep the updater code DRY.

**Comment by marcelgerber** [comment]
Ah, I've just looked into it and sadly, [before React 18, multiple state updates are not batched](https://github.com/reactwg/react-18/discussions/21) (i.e. atomic), and there's no good way to batch them.
This would mean that, in the cases where we currently update both, it would render twice.

Seeing that, and that it works well as it currently is, I'm gonna leave the state as-is with the double object.

**Pull request merged**
