### PR TITLE
Add archive dataset functionality on Admin panel

### LINKED ISSUE #1879: Add an 'Archive dataset' button to dataset pages
## Core problem

The default process for data scientists has become to archive old datasets instead of deleting them entirely. But the current Grapher admin UI doesn't have an `Archive dataset` button.

## Example

https://owid.cloud/admin/datasets/2790

image

## Proposed solution

Add an `Archive dataset` button in the "danger zone", next to the `Delete dataset` button.

The button should run `UPDATE datasets SET isArchived = 1 WHERE id = <DATASETID>`

(cc @spoonerf for tracking)

### PR DESCRIPTION
**Pull request by swaptr**
Initial database query for `isArchived` field:
Initial dataset query

UI change:
UI

Confirmation modal:
Modal

Operation result:
Resulting query

Fixes #1879

### CODE REVIEW

**Comment by swaptr** [comment]
Can someone review this PR? @larsyencken

**Review by marcelgerber — COMMENTED** [review]
Hi, and thank you for the PR!
It's working well, I just found two small things you'll need to change before we merge this PR.

**Comment by swaptr** [comment]
Thanks @marcelgerber for reviewing the PR. I have applied your suggestions.

**Comment by marcelgerber** [comment]
Cool, thank you for your contribution!

**Pull request merged**
