### PR TITLE
Extract grapher and core table types

### PR DESCRIPTION
**Pull request by danyx23**
This PR extracts all types from the `grapher `and `core-table` packages and moves them into the `types `package. This will allow us to freely re-use types finally, e.g. so that the `ChartsRow `type defined in types can specify that the `content `field is a `GrapherInterface`.

### CODE REVIEW

**Comment by danyx23** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3056?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #3054** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3054?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #3056** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3056?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
      * **PR #3064** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3064?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/3056?utm_source=stack-comment).

**Review by ikesau — APPROVED** [review]
lgtm! app compiles & runs, DB migrations run fine 🙂👍

searching `type \w+ = ` in `./packages/@ourworldindata/grapher/src` shows a few places still where we have collections of type declarations in the grapher core library (e.g. `StackedConstants.ts` and `MarimekkoChartConstants.ts`) 

Are those excepted because they're very specific to an internal usecase and closeness is more valuable? Not a blocker either way

**Comment by danyx23** [comment]
Ah yes, nice catch, I have missed some types. I'll merge these and then we can move the remaining ones over in a follow up

**Comment by danyx23** [comment]
### Merge activity

* **Jan 12, 12:47 PM**: @danyx23 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/3056).

**Pull request merged**
