### PR TITLE
add `yarn live-commit` script to show information about deployed commits

### PR DESCRIPTION
**Pull request by MarcelGerber**
This is based off Daniels comment here (https://owid.slack.com/archives/CQQUA2C2U/p1590083865004800), but expanded to also cover staging servers and viewing commit information locally (`--tree` and `--show`).

This is the output of `yarn live-commit playfair --show --tree`, for example:
image

`yarn live-commit` just opens the deployed commit on the live server on github, just like Daniels snippet did.

As for why I'm using `opener` instead of a simple `open`, I'll leave it to [opener](https://www.npmjs.com/package/opener#why):
> Because Windows has `start`, Macs have `open`, and *nix has `xdg-open`. At least [according to some guy on StackOverflow](http://stackoverflow.com/q/1480971/3191). And I like things that work on all three. Like Node.js. And Opener.

I'm running on a Linux/Windows combination, and would like it to work for me too :)

### CODE REVIEW

**Comment by breck7** [comment]
Ah based on this, what if we did something like:

`echo '<meta http-equiv="refresh" content="0; URL=https://github.com/owid/owid-grapher/commit/'$(git rev-parse HEAD)'" />' > source.html`

Then you can just go to [ourworldindata.org|staging|playfair|etc]/source.html to get redirected to the latest commit.

**Comment by danielgavrilov** [comment]
Ok this is a big step up from a bash alias! 😄 

I think we can merge this as is. I have something related I wanted to implement. Will write here but probably better to do it separately:

For me personally, the use case for checking staging server commits is most often to find out which staging server I can use (because we have less _usable_ staging servers than developers). 

So it would be helpful if there is one command that lists every target with the author, message and date of the last commit (`console.table()` might be helpful for structuring this data). 

And while writing that, I just realised that you can also deploy to staging with a dirty working directory (or a commit that doesn't exist on origin), and the last commit is not necessarily representative of the code that is deployed on the server. So.. maybe better to approach that problem separately (or not at all and just create more staging servers).

**Comment by MarcelGerber** [comment]
Ah yes, that sounds like a great and useful idea.
And I think I can add this right to this script, should be easy enough.

Yes, I am aware that deployed commits can be dirty and the commit date is not necessarily the deploy date - one simple workaround would be to just append a `(dirty)` to the commit SHA, a more sophisticated solution would be to also record user, deploy date, and so on in `head.txt`.

Re the shortage of staging servers, maybe it makes sense to revive `explorer` and use it for "normal" deploys just as well? Work on the explorer is currently pretty much stopped anyway, and then you would all get a new staging server _for free_.

**Comment by MarcelGerber** [comment]
Okay, daniels wishes have come true now:
image

One caveat there is that it uses the GitHub API and it only allows 60 unauthenticated requests per hour (I've hit it in testing 😂), but otherwise it works very well :)

**Comment by danielgavrilov** [comment]
Woah! Awesome! This works really well 🙌 

Re the `explorer`: We actually have people externally who are looking at that, and also its HEAD is not merged to master... (totally my fault for leaving it hanging)

Will merge this. I think we don't need to worry about dirty working directories.

**Pull request merged**
