### PR TITLE
chore(deploy): always clear out build dir and run build when deploying

### PR DESCRIPTION
**Pull request by MarcelGerber**
Notion: [Always run cleanTsc & buildTsc pre-deploy](https://www.notion.so/Always-run-cleanTsc-buildTsc-pre-deploy-6b0ff298c65a419b951b0ecc91ab2e2e)

This one is simple.

For reference, on my machine the `buildTsc` steps, with `itsJustJavascript` cleaned out, takes around 60 seconds.

I also checked that this doesn't interfere with any running tsc watch server (`yarn startTscServer`), and have confirmed that this works fine indeed.

### CODE REVIEW

**Comment by danielgavrilov** [comment]
One slightly weird thing is that you can't run the deploy without having first an existing built `itsJustJavaScript` dir. And if the `Deployer.ts` file has changed but has not been rebuilt, then you are running an old deploy procedure.

But that's for another time, I find this to definitely be a big improvement already.

**Review by danielgavrilov — APPROVED** [review]
Feel free to merge & deploy!

**Review by mlbrgl — APPROVED** [review]
LGTM

**Comment by danielgavrilov** [comment]
Actually, what if `yarn cleanTsc` did the `rm -rf`?

**Comment by MarcelGerber** [comment]
This all makes sense to me!
I just pushed a fix that incorporates both of these:
* `cleanTsc` runs `rm -rf itsJustJavascript` (and then also `tsc -b -clean` to get rid of any cache files etc.)
* `buildAndDeploySite` runs `cleanTsc && buildTsc` _before_ the actual deploy script runs, which makes sure that any changes to the deploy script are immediately reflected, and that you can always run a deploy.

**Comment by danielgavrilov** [comment]
🙌 Awesome! 

When I tried something similar a few weeks ago, the prompt “are you sure you want to deploy” I think wasn’t showing up when deploying to `live`, it was terminating without executing anything. (I’m away from laptop until our call, but looks fine to merge if that works!)

**Comment by MarcelGerber** [comment]
Okay, I've been back and forth on this, and you can see that reflected in the commit history.

At one point, I considered re-introducing the `deploy.sh` script to solve _everything_ - the `cleanTsc && buildTsc` step runs before the deploy script, and the live checks run before that so you don't have to wait before being able to confirm the live deploy.

But then I thought this is overthinking it, and I reverted all of it to go back to what we had earlier. How often are we making changes to the deploy script anyway, where we can run into the issue that we are running an old `Deployer` version.

(Basically, the main problem that I had with the earlier version is that the live-deploy confirmation was only happening after the ca. 1-minute long build step finished, and that was annoying)

**Comment by danielgavrilov** [comment]
Looks like you went down some rabbit holes!

> How often are we making changes to the deploy script anyway, where we can run into the issue that we are running an old `Deployer` version.

I agree, and sorry if I sent you down that one! In most cases we are running `startTscServer` in the background, so there is a very small probability we run some stale code _and_ it has some bad consequences. 

As you have it now seems good to me!

**Pull request merged**
