### PR TITLE
datapages misc fixes

### PR DESCRIPTION
**Pull request by mlbrgl**
see linked issues

### CODE REVIEW

**Comment by mlbrgl** [comment]
Current dependencies on/for this PR:
* master
  * **PR #2218** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2218" target="_blank">Graphite</a> 
    * **PR #2233** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2233" target="_blank">Graphite</a> 
      * **PR #2248** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2248" target="_blank">Graphite</a> 
        * **PR #2250** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2250" target="_blank">Graphite</a> 
          * **PR #2259** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2259" target="_blank">Graphite</a> 
            * **PR #2270** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2270" target="_blank">Graphite</a> 
              * **PR #2283** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2283" target="_blank">Graphite</a> 
                * **PR #2286** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2286" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2286?utm_source=stack-comment).

**Review by ikesau — APPROVED** [review]

**Comment by mlbrgl** [comment]
@mlbrgl started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2286).

**Comment by mlbrgl** [comment]
[Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2286) rebased this pull request as part of a merge.

**Comment by mlbrgl** [comment]
@mlbrgl merged this pull request with [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2286).

**Pull request merged**
