### PR TITLE
hotfix(grapher): escape html entities in formatted numbers

### PR DESCRIPTION
**Pull request by sophiamersmann**
Hot fix for #2707

### CODE REVIEW

**Review by Marigold — APPROVED** [review]
Thanks for fixing this! Looks good (some unit tests are failing by the way)

**Comment by sophiamersmann** [comment]
Ah, that makes sense. Let me quickly fix those

**Comment by sophiamersmann** [comment]
oh no, why does it show up as "&lt;" in some charts??

**Comment by sophiamersmann** [comment]
Investigating...

**Comment by sophiamersmann** [comment]
Okay, I'm back at square one. The code that I put in really shouldn't be necessary because React (or JSX) automatically escapes html entities. That usually works (we have many charts with "<") but for this specific slope chart, it doesn't - I'm not sure why because it doesn't look special to me. I'll meet Daniel in a few minutes - I'll discuss this with him. Maybe he has an idea...

**Pull request closed without merging**
