### PR TITLE
chore: add prettier and replace deprecated tslint extension vscode

### PR DESCRIPTION
**Pull request by mlbrgl**
Runs prettier through a tslint rule

---------

I believe one the reasons for keeping the old vscode-tslint extension (https://marketplace.visualstudio.com/items?itemName=eg2.tslint) around was for its ability to fix on save. Now that its replacement has caught up (https://github.com/Microsoft/vscode-typescript-tslint-plugin#differences-with-the-vscode-tslint-extension), I don't see any reason why we should not upgrade.

Another thing is the integration of prettier. So far, I have mimicked the current setup in terms of quotes and semi colons (single quotes, no semis). I don't have a strong opinion on either from a JS/TS perspective, so I would tend to stick to the default settings for both (double quotes, semis).
There is also the constant switching between JS and PHP which makes a stronger case for having semis in JS too.

Any thoughts?

### CODE REVIEW

**Comment by danielgavrilov** [comment]
Thanks Matthieu!

I am in favour of consistent style so having prettier is great. 

The codebase isn’t very consistent with quote usage, so happy to go with the defaults there. I’ve spent a lot of time semicolonless and having them feels odd, but happy to switch.

Feel free to change it as you wish! I’d just prefer that we run `prettier` on all files before merging so that future commits don’t get polluted with formatting.

**Comment by danielgavrilov** [comment]
Oh and I noticed TSX quotes are still double and should probably be consistent with whatever we decide.

**Comment by mlbrgl** [comment]
Thanks for the feedback. Yep, JSX quotes are treated differently (https://prettier.io/docs/en/options.html#jsx-quotes), one more reason to use doubles. Let's save ourselves some keystrokes and nagging "~~" and not use semicolons.

I'm running a bake on staging to test that everything behaves as it should, and I'll commit the prettified codebase here.

**Comment by mlbrgl** [comment]
@danielgavrilov all files are prettified and everything looks good on staging. We should be good to go.

**Pull request merged**
