### PR TITLE
All charts block

### PR DESCRIPTION
**Pull request by ikesau**
A very straightforward PR thanks to Matthieu's clean API design of the component for WordPress.

To test:

```
title: All charts test page
excerpt: All charts
type: topic-page
[+body]
{.all-charts}
heading: Interactive charts on Poverty
[.top]
url: https://ourworldindata.org/grapher/size-poverty-gap-countries
[]
{}
[]
```

And in the admin, tag this page with the "Poverty" tag.

### <samp>🤖 Generated by Copilot at c8f1c15</samp>

This pull request adds support for the `all-charts` block type in the grapher and the CMS. The `all-charts` block allows displaying a list of related charts in a gdoc based on tags or a custom selection. The pull request defines new types, constants, functions, and components for the `all-charts` block, and integrates them with the existing modules for parsing, converting, and rendering gdocs. The pull request also refactors some code for other block types to use constants for their headings, and adds examples and styles for the `all-charts` block.

### CODE REVIEW

**Comment by mlbrgl** [comment]
@ikesau the chart renders based on the available space in the parent block, so something likes this lets the chart knows how tall to render:
```
figure[data-grapher-src] {
    height: $grapher-height;
}
```

see also:
- https://github.com/owid/owid-grapher/blob/51b6be67ab0f6580e41c2d8cba8d5663e8d7e62b/site/DataPageContent.scss#L319-L321
- https://github.com/owid/owid-grapher/blob/51b6be67ab0f6580e41c2d8cba8d5663e8d7e62b/site/css/content.scss#L97-L100

**Comment by mlbrgl** [comment]
@ikesau is this ready for review?

**Comment by ikesau** [comment]
@mlbrgl yup! good to go 🙂

**Comment by mlbrgl** [comment]
- [ ] copilot:summary
- [ ] is the branch up-to-date with master?
- [ ] what problem is being solved here?
- [ ] what solution has been chosen?
- [ ] are there other solutions?
- [ ] is the scope clear, well-defined and small?
- [ ] could a flow chart / sequence diagram / architecture diagram help?
- [ ] what is the happy path?
- [ ] could the code be easier to read and understand?
- [ ] can I help increase our confidence in the implementation by contributing tests?
- [ ] should some errors be made more prominent?
- [ ] what is missing, what should have been added / done / changed but hasn't?

**Review by mlbrgl — COMMENTED** [review]
Looks good to me! I paused for a moment about the parallel support for `key charts` and `top`.

The concept of "most important charts for a topic" is what key charts are for, so any `top` chart on a topic page should really be a key chart.

Outside of topic pages, we might be making a point for which only a few charts are relevant, which would make the case for this property. However, this block brings all charts of the current doc's topics along for the ride, so I don't see it used like that in this current state.

So, I'm curious as to whether we're anticipating use cases beyond:
- show all charts on a particular topic or set of topics (promoting key charts at the top, without fine-grained control over the absolute order)
- show an arbitrary set of charts in a very precise order

**Review by mlbrgl — APPROVED** [review]
Otherwise 👍

**Comment by ikesau** [comment]
Thanks @mlbrgl !

The `top` feature was a faster way to enable this [request from the authors](https://owid.slack.com/archives/C03NA1B2P1U/p1682671268828349?thread_ts=1682668766.796469&cid=C03NA1B2P1U) to have a way to order key charts in ways that were non-alphabetical, without having to refactor the key charts data model.

I'll raise the point with the P&D group that we could change this component to not require a category at all, but I'll hold off on implementing that unless they want it.

**Pull request merged**
