### PR TITLE
2227-datapages-automatically-populate-all-charts-block

### PR DESCRIPTION
**Pull request by mlbrgl**
see #2227 
_Note: this stacked PR doesn't target master._

- [x] 
### <samp>🤖 Generated by Copilot at 34041ac</samp>

This pull request adds a feature to automatically fetch and display related charts for datapages and graphers based on the variable id. It implements a new function `getRelatedChartsForVariable` in `db/wpdb.ts` to query the database, and modifies the `DataPageContent` and `GrapherBaker` components to use the results. It also updates the `DataPageJsonTypeObject` type definition to reflect the changes.
- [x] is the branch up-to-date with master?
- [x] what problem is being solved here?
Authors need to manually specify the list of charts a variable is used in, when this could be automated
- [x] what solution has been chosen?
Getting the list of related charts from the database
- [x] are there other solutions?
- [x] is the scope clear, well-defined and small?
- [x] could a flow chart / sequence diagram / architecture diagram help?
- [x] what is the happy path?
  - do not add / remove the `relatedCharts` key in the JSON ([example](https://github.com/owid/owid-content/blob/master/datapages/587683.json)).
  - (optional) set `"status":"published` in the data page JSON
  - ⚠️ If editing the JSON for testing, do it on staging or locally but do not commit). _This has been done on the staging site already, but probably needs to be done again if further pushes reset the owid-content repo._
  - see the "Related charts" section be populated by charts ([preview](http://staging-site-2227-datapages-automatically-populate-all-charts-b/admin/grapher/banana-production), [baked](http://staging-site-2227-datapages-automatically-populate-all-charts-b/grapher/banana-production))
- [x] could the code be easier to read and understand?
- [x] can I help increase our confidence in the implementation by contributing tests?
- [x] should some errors be made more prominent?
- [x] what is missing, what should have been added / done / changed but hasn't?

When going live:
- [ ] un-nest `relatedCharts.items` in all datapage JSON (or remove them?)

### CODE REVIEW

**Comment by mlbrgl** [comment]
@JoeHasell the `relatedCharts` key in the data page JSON is now overriding the list of charts automatically pulled from the database. I can go through all the data page JSONs and remove the manual selection if you want to have the automatic behaviour across all data pages.

**Comment by mlbrgl** [comment]
Current dependencies on/for this PR:
* master
  * **PR #2233** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2233" target="_blank">Graphite</a> 
    * **PR #2248** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2248" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2248?utm_source=stack-comment).

**Review by ikesau — APPROVED** [review]

**Comment by mlbrgl** [comment]
@mlbrgl started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2248).

**Comment by mlbrgl** [comment]
@mlbrgl merged this pull request with [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2248).

**Pull request merged**
