### PR TITLE
Dev: remove componentWillMount calls

### PR DESCRIPTION
**Pull request by breck7**
This seems to works and looks okay but not 100% certain I'm getting the React lifecycle + mobx stuff right.

### CODE REVIEW

**Comment by shaahmad** [comment]
I haven't looked too deeply into this, but is it possible to avoid using a `reaction` here?
For these reasons: https://github.com/owid/owid-grapher/pull/544#discussion_r470149021

**Comment by breck7** [comment]
> I haven't looked too deeply into this, but is it possible to avoid using a `reaction` here?
> For these reasons: [#544 (comment)](https://github.com/owid/owid-grapher/pull/544#discussion_r470149021)

Good call! I'll remove.

Quick scan of our mobx function usage:
- 15 reactions
- 57 runInActions
- 4 whens
- 14 autoruns

I like the decorators, but I wonder if we could get rid of all of these? In general I find them prone to bugs and hard to test.

**Comment by shaahmad** [comment]
> > I haven't looked too deeply into this, but is it possible to avoid using a `reaction` here?
> > For these reasons: [#544 (comment)](https://github.com/owid/owid-grapher/pull/544#discussion_r470149021)
> 
> Good call! I'll remove.
> 
> Quick scan of our mobx function usage:
> 
> * 15 reactions
> * 57 runInActions
> * 4 whens
> * 14 autoruns
> 
> I like the decorators, but I wonder if we could get rid of all of these? In general I find them prone to bugs and hard to test.

Interesting. I do see the valid use cases for these, but they are easy to abuse. On a quick glance, looks like they are more abused than not in our codebase.

**Comment by MarcelGerber** [comment]
@breck7 do you still want to remove the `reaction` stuff here?

(but I guess your big PR is of higher priority right now)

**Comment by breck7** [comment]
I have cherry-picked this one into my big rebase.

**Pull request closed without merging**
