### PR TITLE
add basic stacked bar chart

### PR DESCRIPTION
**Pull request by sherinkurian**
Add support for Stacked Bar Chart

1. Add legend (uses legend used by Scatter Plots)
2. Add tooltip on hover
3. No scale on X-Axis but still assumes X-Axis to be years

screenshot 2018-07-08 18 14 47

screenshot 2018-07-08 18 18 49

### CODE REVIEW

**Comment by mispy** [comment]
Awesome that you looked into this one! I'm back from my travels now (was in Europe for the last few weeks) and working full-time again so will be more responsive. I'll be looking into creating a better data export this week.

Here is how [this line chart](https://ourworldindata.org/grapher/natural-disaster-deaths?country=All%20natural%20disasters+Drought+Earthquake+Epidemic+Extreme%20temperature+Extreme%20weather+Flood+Landslide+Mass%20movement%20(dry)+Volcanic%20activity+Wildfire) looks as one of your stacked bar charts:

natural-disaster-deaths

The legend should look similar to scatter or slope chart-- the main difference is that it won't be using a separate color variable, but rather choosing colors in the same way line charts or maps do

I think the default behavior for now should be to present a labeled bar for each year with available data. Aggregation over decades or other time ranges would be nice to have but a bit more complicated

**Comment by sherinkurian** [comment]
Thanks for the review and welcome back! 

+1 on the default behavior recommendation to keep it simple. i will make more changes.

**Comment by mispy** [comment]
Fantastic! Hannah will be really happy to have these implemented. You even made them work correctly in both multivariable and multientity cases.

Agreed that the hover behavior isn't essential for this chart. It is kinda nice to have for consistency across chart types. The color behavior should match between the legend and the chart (i.e. it should make the unhovered bar sections to grey).

More generic handling of data association with axes is something that could be improved across all the chart types, yep. In theory the discrete and stacked bar chart types could be configuration states of the one type of chart. It's not a huge priority though.

These are almost production-ready, I think!

deaths-risk-factor-15-49years

 Some small tweaks left:

- It should handle the case when there isn't enough space for all the year labels (especially for mobile). Fancy solution would be to rotate them, but hiding the overlaps would also be fine for now.

reported-number-of-smallpox-infections-by-world-region

- The x axis labels should be centered underneath the bars
- The legend text should be a bit less bold
- The axis margins and tick formatting should otherwise match the other chart types (e.g. 7000000 should appear as 7 million)
- Since the Y Axis settings on the Customize tab don't make sense for a stacked bar chart, they should be hidden in the editor
- The hover box text should match the line chart hover box (Y in X) for now, making sure to use the axis unit formatting

Mostly just little consistency things :) Thanks very much for your help!!

**Comment by sherinkurian** [comment]
Thank you for the thorough feedback and kind words! I will get on it 💪

**Comment by sherinkurian** [comment]
hi Jaiden, this is almost ready for the most part. I am not sure about the way it looks on mobile though.

screenshot 2018-07-24 19 26 38

versus

screenshot 2018-07-24 19 26 45

I will play with it more. When you said rotation, did you mean flipping the axis or supporting some kind of horizontal scrolling.

**Comment by mispy** [comment]
These are great, thanks Sherin! 👍 I'm just making some finishing changes, then will make them available to the authors to play with.

**Comment by HannahRitchie** [comment]
Hi Sherin!

We are now definitely best friends! I love stacked bar charts (think they're really useful) and so great that we now have them in the grapher. Thanks so much for your work on this!

I have been playing with making various stacked bar charts in the grapher, and all is working perfectly. It's very intuitive for users to create, and visually there is really nothing I would tweak or change. I guess all of the key issues, Jaiden ironed out above.

Thanks again for your help! This is really great work.

deaths-by-age-group-stacked

**Comment by eoo-owid** [comment]
Hi Sherin! Just wanted to say again what Hannah and Jaiden have already said – thanks so much! This is really a super helpful tool for us! 

I'll let you know if any more specific feedback comes to mind later. But I just wanted to say thanks now :)

**Comment by sherinkurian** [comment]
feel free to send any feedback :) 

Jaiden is already making it fancier with animations and all 💪

**Pull request merged**
