### PR TITLE
Local env for cloudflare functions with makefile

### PR DESCRIPTION
**Pull request by mlbrgl**
This PR adds local development support for Cloudflare Pages functions.

It integrates the wrangler dev server to the `make up.full` command.

### CODE REVIEW

**Comment by mlbrgl** [comment]
Current dependencies on/for this PR:
* master
  * **PR #2956** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2956?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #2978** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2978?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2978?utm_source=stack-comment).

**Comment by danyx23** [comment]
Could you document this a bit more please? It's unclear to me what this does - which kinds of things does the cf functions dev server expose?

Please also integrate it into the `make up` command.

There is a `--compatibility-date` flag in the `startLocalCloudflareFunctions` script call - when is that supposed to be updated? Maybe add a comment there?

**Comment by danyx23** [comment]
I just saw that this is documented in the readme in the next PR - so mostly including this in `make up` remains here :)

**Comment by mlbrgl** [comment]
Thanks! Sorry for spreading the docs across multiple PRs!

Yes, I haven't fully dived into the other CF functions code yet, and I didn't want to blindly add this startup command. Feel free to commit to this PR though if you think it's good to go!

**Review by danyx23 — APPROVED** [review]
LGTM!

**Comment by mlbrgl** [comment]
### Merge activity

* **Jan 11, 12:29 PM**: @mlbrgl started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2978).

**Pull request merged**
