### PR TITLE
feature(baking): add variables.type column that explicitly specifies type information

### PR DESCRIPTION
**Pull request by Marigold**
See the [original proposal](https://www.notion.so/owid/2023-03-10-Proposal-define-ordered-value-sets-for-ordinal-variables-dd15d4b5fdb74292b9420923981b2a1c).

Add column JSON column `variables.type` that can contain explicit type of a variable. Some examples are `{"type": "int"}`, `{"type": "string"}` or `{"type": "ordinal", "sort": ["Low", "Medium", "High"]}`. If null, then type is determined from data (as int, float, string or mixed) to be backward compatible.

If you're trying this locally, first apply the latest migration with `yarn buildTsc && yarn runDbMigrations` and then set `type` for income groups
```sql
update variables
set type = '{"type": "ordinal", "sort": ["Not categorized", "Low income", "Lower-middle income", "Upper-middle income", "High income"]}'
where id = 42563
```

Baked metadata file for that variable would then contain following fields:
```
{
  ...
  "type": "ordinal",
  "sort": ["Not categorized", "Low income", "Lower-middle income", "Upper-middle income", "High income"]
}
```

Related: #1692, #1324

### CODE REVIEW

**Comment by sophiamersmann** [comment]
I made the (minimal) changes necessary to sort the scatterplot legend using the new metadata field (it works!).

I'm unsure though what's the best way to let Grapher know that a variable is known to be "ordinal". If I am understanding correctly, Grapher seems to ignore the metadata field `type` at the moment and simply marks every value column as `NumberOrStringColumn` (which is essentially a "mixed" type):

https://github.com/owid/owid-grapher/blob/77d3bcd664fc95d52ef3764e629b08b658b833a5/packages/%40ourworldindata/grapher/src/core/LegacyToOwidTable.ts#L581-L583

A code comment regarding `NumberOrStringColumn`:

https://github.com/owid/owid-grapher/blob/77d3bcd664fc95d52ef3764e629b08b658b833a5/packages/%40ourworldindata/core-table/src/CoreTableColumns.ts#L585-L593

I'm not confident making changes at the moment. I'll have a chat with Marcel once he's back and then get back to this :)

**Comment by sophiamersmann** [comment]
After discussion with @danyx23 and @samizdatco, how to best represent ordinal variables remains an open question. The options are:

1. Store ordinal variables as string values and attach an ordering to them (current behaviour, inspired by [Vega types](https://vega.github.io/vega-lite/docs/type.html#ordinal))
2. Store ordinal variables as numerical values (that define an ordering implicitly) and attach labels to them

I believe (1) would make our life a bit easier since turning a categorial variable into an ordinal one would require us to add a "sort" array but no data migration would be needed. (Though we do have some ordinal variables that are currently stored as numerical values as well.) The advantage of (2) is that the extra bit of encoded information (negative/neutral/positive) would help us auto-pick appropriate colour palettes (e.g. if we had an ordinal variable with categories "disagree" / "don't care" / "agree" encoded by -1, 0, 1, Grapher could infer that a diverging colour palette is needed).

One additional thing to keep in mind, and this might be controversial, is that I think it would be beneficial to attach an ordering to the "continents" variable as well. We could then customise the order of the continents such that "North America" and "South America", for example, would appear next to each other in legends ([example chart](https://ourworldindata.org/grapher/gdp-per-capita-vs-staff-compensation-as-share-of-total-expenditure-in-primary-public-education)). If we wanted to do this, approach (1) would be less awkward.

**Comment by Marigold** [comment]
(It doesn't make a difference on ETL end, so I yield and let you decide.)

**Comment by marcelgerber** [comment]
Ideally, our new handling of ordinal data would be able to cover:
- all the cases where we already have ordinal data points, and are currently using (unordered) categorical legends, with underlying string data ([example](https://ourworldindata.org/grapher/carbon-tax-instruments))
- all the cases where we already have ordinal data points, and are currently encoding them as numbers, with custom labels applied in the legend ([example](https://ourworldindata.org/grapher/public-events-covid))
- bonus points if it can handle scenarios where we mix ordinal categories with actual numerical observations ([example](https://ourworldindata.org/grapher/year-country-was-certified-free-of-guinea-worm-disease))

---

In terms of data representation, I would prefer some sort of shorthand for categorical values, which we would then put into the metadata file, similar to how we already handle entities (where there's a mapping `entityId -> entityName` in `metadata.json`, and the `data.json` only contains the entity ids).
The reason here is that the (uncompressed) data files can become very unwieldy very quickly otherwise, and we will always have a restricted domain of possible categorical values.

(See also: [quick analysis of categorical variables that are currently in use](https://docs.google.com/spreadsheets/d/1TsIirQbKim_YIgho5B7tkalR062WKuFKiGCW3mfdL7E/edit?usp=sharing))

What's unclear to me at this point, though, is how we would differentiate "actual" numeric values from named values, then, in the case of mixed types.

**Comment by marcelgerber** [comment]
> My thinking was that we decide on one strategy to represent ordinal data and then migrate offending ordinal variables to the new system, therefore reducing complexity in the long run.

Ah, yes, that's exactly what I mean. Definitely pro reducing complexity here.



> Do you have an estimate of how many variables we have that have a mixed type with numerical and ordinal categories?

Yeah, as you say this is a tiny minority. Not a pressing need.

**Comment by sophiamersmann** [comment]
For reference: the [original proposal](https://www.notion.so/owid/2023-03-10-Add-type-information-to-variables-dd15d4b5fdb74292b9420923981b2a1c) has been updated to reflect the outcome of recent discussions

**Comment by Marigold** [comment]
We've talked about this recently and have an appetite for finishing it.

**Comment by Marigold** [comment]
Hold on bot!

**Comment by Marigold** [comment]
> If we wanted to resurrect this PR, how much effort/time do you think it would be on your part?

I'm not sure, but we put it on this cycle's list. I'll prioritize it to unblock you.

**Comment by Marigold** [comment]
Killed in favour of https://github.com/owid/owid-grapher/pull/3362

**Pull request closed without merging**
