### PR TITLE
Add Cypress for e2e tests (follow up)

### PR DESCRIPTION
**Pull request by mlbrgl**
Follow up on https://github.com/owid/owid-grapher/pull/321.

https://github.com/owid/owid-grapher/blob/cd67694faa2b556a300ea4b031a7b7ef73a1cbac/charts/DataSelector.tsx#L16

_window.MouseEvent is required by cypress, however it is being emptied as a result of webpack defining global === window. The idea was probably to check which environment the code was running in (node or browser), which is ineffective in this case as global is defined in both._

@danielgavrilov global.MouseEvent = {} was running in both node and the browser. Now it's running in none and I'm seeing no difference either way. Any idea what that "Metadata reflection hack" is/was about?

### CODE REVIEW

**Comment by danielgavrilov** [comment]
> global.MouseEvent = {} was running in both node and the browser. Now it's running in none and I'm seeing no difference either way. Any idea what that "Metadata reflection hack" is/was about?

Nope! Seems very old, possibly related to a quirk in some older version of TypeScript? Anyway, removing it seems fine, can't notice any difference either, everything including typechecking seems to work.

**Comment by danielgavrilov** [comment]
@mlbrgl My `yarn` install seems to insist on making this change to the yarn lockfile:

```diff
-"request@github:cypress-io/request#b5af0d1fa47eec97ba980cde90a13e69a2afcd16":
+request@cypress-io/request#b5af0d1fa47eec97ba980cde90a13e69a2afcd16:
```

Could you maybe rerun `yarn` on your machine and check if you get the same? Maybe it's a version issue, I'm on `1.22.4`.

**Comment by mlbrgl** [comment]
@danielgavrilov thanks for the review! 

Regarding the yarn.lock issue:
- running `yarn`on 1.22.0 -> no difference
- updating yarn to 1.22.4 + running `yarn` -> no difference
- uninstalling cypress + `yarn add -D cypress` on 1.22.4 -> no difference
- manually editing yarn.lock with your change + `yarn` -> the change is not reverted.

I still don't know why this is happening but if that can get your yarn to stop complaining, it seems harmless.

**Comment by danielgavrilov** [comment]
@mlbrgl Really sorry that it took me _forever_ to merge this.

I run into timeouts when running the tests because `/cancer` takes longer than 60sec to load on my machine:

```
CypressError: Timed out after waiting '60000ms' for your remote page to load.

Your page did not fire its 'load' event within '60000ms'.

You can try increasing the 'pageLoadTimeout' value in 'cypress.json' to wait longer.
```

I think it possibly never loads, so this is likely an issue with my local environment. Will merge so we can build on top of this (finally).

**Pull request merged**
