### PR TITLE
Enhance staging refresh script

### LINKED ISSUE #1383: More consistent WORDPRESS_DB_PASS(WORD) env var
## Core problem

Inconsistency on Wordpress DB var name:
[.env.example.full](https://github.com/owid/owid-grapher/blob/5b9bfe760e4c2f99e68db7a4207db36ff95c4144/.env.example-full#L14): `WORDPRESS_DB_PASS`
[.env.example](https://github.com/owid/owid-grapher/blob/5b9bfe760e4c2f99e68db7a4207db36ff95c4144/wordpress/.env.example#L3): `WORDPRESS_DB_PASSWORD`

## Proposed solution

`WORDPRESS_DB_PASSWORD` -> `WORDPRESS_DB_PASS`

## Context
Follow-up to #1369

### PR DESCRIPTION
**Pull request by mlbrgl**
- in staging refresh script: fail early if required env vars are not defined
- resolves #1383 
- remove the need for `GRAPHER_*` env vars in `wordpress/.env` by making the refresh script dependant on the top level `.env`

TODO for each environment:
- local & ⚠️ live : rename `WORDPRESS_DB_PASSWORD` -> `WORDPRESS_DB_PASS` in `wordpress/.env` and `.env`
- staging & ⚠️ live: deploy both admin and wordpress codebases (`buildAndDeploySite`, `deployWordpress`)
- staging: cleanup `GRAPHER_*` env vars in `[staging_name]-wordpress/.env`

## Outdated
- update wordpress example env file (`wordpress/.env.example`) to match the new vars requirements:
    - `GRAPHER_DB_USER`
    - `GRAPHER_DB_PASSWORD`

Manual updates to staging servers `[codename]-wordpress/.env` required to add:
- `GRAPHER_DB_USER`
- `GRAPHER_DB_PASS`

These are the same as the vars of the same names defined in `[codename]/.env`

### CODE REVIEW

**Comment by mlbrgl** [comment]
Switching back to draft. Moving the refresh script to the top repo might actually be a better idea, since it will remove the need to maintain a duplicate of the GRAPHER_* env vars in `./wordpress`

**Comment by mlbrgl** [comment]
@ikesau thanks for reviewing! Yes if that doesn't mess up any current work you might have on there, that'd be good for confirming I didn't leave out some of the required manual updates.

**Comment by ikesau** [comment]
Hey @mlbrgl - I'm running into some issues migrating my staging environment with this branch. Let's pair on this when you're next free :)

**Comment by ikesau** [comment]
Alright, good to merge!

**Pull request merged**
