### PR TITLE
Upgrade tag autocomplete + UX

### PR DESCRIPTION
**Pull request by mlbrgl**
see [demo](https://owid.slack.com/archives/C014SGT6W9X/p1694539715117499)

- reduce guessing by seeing all tags available
- autofocus for speeding up keyboard filtering
- validate selection by pressing "esc"
- improved styles

### CODE REVIEW

**Comment by mlbrgl** [comment]
Current dependencies on/for this PR:
* master
  * **PR #2625** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2625" target="_blank">Graphite</a> 
    * **PR #2627** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2627" target="_blank">Graphite</a> 
      * **PR #2635** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2635" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2635?utm_source=stack-comment).

**Review by ikesau — APPROVED** [review]
Lovely!

Tested locally on gdocs, posts, and charts. All working! 💪

**Comment by mlbrgl** [comment]
@ikesau thanks for the review!

**Comment by mlbrgl** [comment]
### Merge Activity

* **Sep 15, 11:29 AM**: @mlbrgl started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2635).

**Pull request merged**
