### PR TITLE
Start moving component styles to typed CSS in the Component TSX files

### PR DESCRIPTION
**Pull request by breck7**
In this PR I:

- Move styling of comparison lines from SVG attributes to CSS
- Add CSS classes to the elements to make it easy for designers and devs to interactively experiment with designs in dev tools
- Move the CSS for this component to the TypeScript to keep components self contained and modular
- Render a Style Tag with the CSS with the render of the rest of the element so that the SVG/PNG export works without including external CSS

I looked at a number of ways to write CSS in TypeScript with React and none of them seemed to be ideal. I think this method is close to as simple as you get, except there is the one downside in this current implementation where the style tag is added per instance instead of once per class. A number of ways we could fix that but wanted to get feedback first on this approach.

### CODE REVIEW

**Comment by breck7** [comment]
3 tested packages that implement this pattern we might want to use instead:

- https://github.com/Khan/aphrodite
- https://github.com/FormidableLabs/radium
- https://cssinjs.org/react-jss/?v=v10.1.1

**Comment by danielgavrilov** [comment]
Looks good to me! 

One other use case is modifying the charts in Illustrator, and using them as starting points for the static charts. I think Illustrator should support the inline CSS, but I don't have it installed to check (easiest would be to ask one of the authors?)

**Comment by mlbrgl** [comment]
> 3 packages with tests that implement this pattern that we might want to use instead:
> 
> * https://github.com/Khan/aphrodite (looks good)
> * https://github.com/FormidableLabs/radium
> * https://cssinjs.org/react-jss/?v=v10.1.1

@breck7 interesting approach! I guess you also considered styled-components, what made you decide against it?

**Comment by breck7** [comment]
> One other use case is modifying the charts in Illustrator, and using them as starting points for the static charts. I think Illustrator should support the inline CSS, but I don't have it installed to check (easiest would be to ask one of the authors?)

I don't have Illustrator but tried BoxySVG and did hit some somewhat related issues. I think the net benefits from moving away from inline styles here aren't actually too substantial and will keep that idea orthogonal to this comparison line issue.

> I guess you also considered styled-components, what made you decide against it?

Styled-components looks very cool and easy to start with but I wasn't sure exactly how easy it would be to move an existing site toward. Regardless I think it makes sense to split a potential CSS refactor away form this comparison line issue.

**Pull request merged**
