### PR TITLE
🐛 (facets) show axes for no data charts /  TAS-552

### PR DESCRIPTION
**Pull request by sophiamersmann**
Show axes for charts without data, fixes https://github.com/owid/owid-grapher/issues/2127

Implemented as part of an effort to create a set of climate charts, see draft charts on [this staging site](http://staging-site-stacked-bar/admin/charts)

## Summary

- Rather than figuring out the first left chart that has data and show the axis for it, we simply always show the axis, even if there is no data
    - In faceted charts, that solves a particular bug that we were struggling to fix, and I also think it looks better – it gives the overall layout more structure and is less disruptive
    - In normal/unfaceted charts, rendering an axis although there is no data looks a bit dumb, but I think it's an okay compromise
- I also realised that I broke the `NoDataModal` when I worked on the entity selector redesign – the 'edit entities' button [don't currently show up](https://ourworldindata.org/grapher/life-expectancy?country=Test) (luckily almost, since the button would be broken if the entity selector is plotted into the side panel) – after checking in with Marwa, we decided to remove the buttons alltogether; instead, we show a help message
- Technically, we implicitly know when we're currently faceting (if both `canChangeEntity` and `canAddEntities` are undefined), but I don't want to rely on that, and I also don't want to start passing an `isFacet` down to our charts – I think it's ok like this

## To do

- ~Use text wrap to make sure the text doesn't overflow~ okay like this, I think
- [x] Don't show the help message for static charts

## Screenshots

| Before  | After  |
| ------- | ------ |
| Screenshot 2024-06-21 at 15 34 32  | Screenshot 2024-06-21 at 15 24 18 |
| Screenshot 2024-06-21 at 15 34 10 | Screenshot 2024-06-21 at 15 32 18 |

👆🏻 [Line chart](http://staging-site-no-data-axes/grapher/life-expectancy?time=earliest..1930&facet=entity&country=WLF~FRA~SWE~ASM) / [Bar chart](http://staging-site-no-data-axes/grapher/natural-disasters-by-type?facet=entity&country=Landslide~All+disasters~All+disasters+excluding+earthquakes~All+disasters+excluding+extreme+temperature~Drought~Dry+mass+movement~Earthquake~Extreme+temperature~Extreme+weather~Fog)

<details><summary>More screenshots</summary>
<p>

Having a single zero line looks a bit dumb:
Screenshot 2024-06-26 at 13 38 02

Screenshot 2024-06-25 at 18 33 32

The outer axis labels are cut:
Screenshot 2024-06-25 at 18 34 15

Well...
Screenshot 2024-06-25 at 18 35 37

</p>
</details>

### CODE REVIEW

**Comment by sophiamersmann** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3735?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#3735** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3735?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#3733** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3733?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3726** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3726?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3725** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3725?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3722** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3722?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @sophiamersmann and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by marcelgerber** [comment]
Didn't have time for a proper review yet, but one thing comes to mind about this one:

The "No matching data" text is only shown when rendered to HTML; it is never part of a SVG / png.
This meant that before this PR, we were only rendering a white block in place of the charting area (which wasn't great). Now, we're rendering a full, but empty, axis, which might be even more misleading.

**Comment by sophiamersmann** [comment]
Ah, good point. I removed the buttons in this PR, so we could just turn the foreignObject into SVG.

**Review by marcelgerber — COMMENTED** [review]
Nice, nothing to complain about here.

Again, would be great if we can now actually render the text to SVG - I think there shouldn't be much preventing us from that at this point.

**Review by marcelgerber — APPROVED** [review]
Nice!

One small thing I noticed is that this has slightly degraded stacked bar charts, in that they display a single-entity legend again:

CleanShot 2024-07-02 at 17 27 06

**Pull request merged**
