### PR TITLE
enhance(mysql): exclude pageviews from export

### PR DESCRIPTION
**Pull request by Marigold**
Part of https://github.com/owid/analytics/pull/70

### CODE REVIEW

**Review by marcelgerber — COMMENTED** [review]
So, I know that https://github.com/owid/analytics/pull/70 creates/updates this table every day.
However, that only happens on `live` and not on any other server or local environment. And if the table doesn't exist and this script is run, then `mysqldump` will fail with an error.

So, in my mind we should also create a proper migration so that our database schema is consistent no matter in what environment we came up with it. In particular, this also means that the schema in the new db-tests will be the same as the one we get from importing the live database.

Curious to know what @danyx23 thinks.

**Comment by Marigold** [comment]
@marcelgerber good points, I'll add the migration that creates the table. I guess we don't need TypeORM definition yet.

**Comment by danyx23** [comment]
Agreed - adding a migration is the way to go. Otherwise this looks good and I'm looking forward to having this!

**Comment by Marigold** [comment]
Added that migration and tested that `node itsJustJavascript/db/exportMetadata.js` still works. @marcelgerber is this good to go?

**Review by marcelgerber — APPROVED** [review]

**Pull request merged**
