### PR TITLE
Add edge case test: row & column delimiter used in key & value

### PR DESCRIPTION
**Pull request by danielgavrilov**
Sorry for the messiness, there's probably a better way to write up that test case

### CODE REVIEW

**Comment by breck7** [comment]
this is great, thanks! will fix later today when i am at my keyboard wih a "" key

**Comment by MarcelGerber** [comment]
What's the status of this?

**Comment by breck7** [comment]
I think this one ties in with "change %20 to plus in urls".

**Comment by breck7** [comment]
Added this here: f8a42112f

**Pull request closed without merging**
