### PR TITLE
Timeline Tooltips + Upgrades

### PR DESCRIPTION
**Pull request by shaahmad**
**Live on [Nightingale.](https://nightingale-owid.netlify.app/grapher/number-without-clean-cooking-fuel?tab=chart)**

ezgif-6-952d16debb7e

This PR:
- creates tooltips on the Timeline that show the currently selected date, and fade after 2 seconds.
- adds padding around the Timeline to make it easier to click.
- fixes a small Timeline bug where the Handle jumps on click.

### CODE REVIEW

**Comment by MarcelGerber** [comment]
> snap handles if within 1 year

Hm, that doesn't seem to work. See for example this chart: https://ourworldindata.org/grapher/human-rights-violations?tab=chart&time=2013..2014

Maybe you need to compare `startYearRaw` and `endYearRaw` instead?

**Comment by shaahmad** [comment]
So the final behavior I went with was to round when handles are within 1 year of each other. If they are less than half a year apart, they combine into one handle. If they are closer to 1 year apart, they snap apart. This is to prevent accidentally snapping handles together when you want to compare 2 years.

**Comment by shaahmad** [comment]
Ah, but in the process of looking through the code, I found several related issues and corrected them. Let me know if what you're referring to still exists!

**Comment by MarcelGerber** [comment]
Still there 😶
But it's more of an edge case, so you don't need to pour endless resources into fixing that little annoyance.

Snapping them together when only one year is displayed works, but not for only 2 years.

**Comment by shaahmad** [comment]
^^ The issue above has been resolved.

**Pull request merged**
