### PR TITLE
enhance(admin): exclude archived datasets

### PR DESCRIPTION
**Pull request by Marigold**
Exclude archived datasets from `admin/datasets` and other lists (sources, variables, etc.). Instead of manually adding WHERE conditions we could have a `active_datasets` or `unarchived_datasets` view with the `not isArchived` filter.

### CODE REVIEW

**Comment by marcelgerber** [comment]
pulling in @danyx23 here as our opinionated SQL guy: what do you think? should we create a view instead?

**Comment by danyx23** [comment]
I thought about this before, yes. I think adding a view for it is nicer. Do we need to consider if that propagates correctly everywhere? For grapher deployments its fine (except that the migration has to be run manually when deploying which we should fix at some point). Maybe we'll want the same view in bigquery then as well? Anywhere else?

**Comment by marcelgerber** [comment]
> except that the migration has to be run manually when deploying which we should fix at some point

I don't think that's the case?
Well, we're gonna see either way...

**Review by marcelgerber — APPROVED** [review]
yep looks good now, thank you!

**Comment by danielgavrilov** [comment]
Migrations run automatically on deploy

https://github.com/owid/owid-grapher/blob/6a5729d34556a241bbc38b0c1cf72e105c6af3a2/baker/Deployer.ts#L225

**Comment by danyx23** [comment]
Right, sorry - I had mixed that up in my head with the issue that migrations that are still in your itsJustJavascript folder locally are run to migrate which bit me once

**Pull request merged**
