### PR TITLE
chore: update to node 18

### LINKED ISSUE #1645: Repo is incompatible with Node 18
## Description

Currently the project can't be run using Node.js 18, only v16 or v17. We should fix this as node 16 will enter maintenance mode in October 2022 and its best to keep things relatively up-to-date and compatible to avoid potentially painful migrations later on. 

## Expected behaviour

Running `make up.full` with nodejs v18 is successful. 

## Steps to reproduce

1. `nvm use 18`
2. `make up.full`
3. See error:

```
eslint-plugin-jsdoc@37.9.7: The engine "node" is incompatible with this module. Expected version "^12 || ^14 || ^16 || ^17". Got "18.2.0"
```

This is a sub-dependency of the `@wordpress/scripts` dependency which is currently at `v19.2.3`. The latest version of that package is `v24.0.0`. I believe upgrading to the latest version of that will fix the issue, but I'm not sure what potential changes we'll have to make to do that.

### PR DESCRIPTION
**Pull request by marcelgerber**
Resolves #1645.

Update to using [Node 18](https://nodejs.org/en/blog/announcements/v18-release-announce) everywhere.
The main new feature is builtin support for `fetch`, but we also get some new APIs like `.findLastIndex`.

~I haven't figured out yet how we can deploy this to a staging server, since we use the global Node 16 we have running. Have to figure that out at some point in the future...~

Our staging servers (the actual ones, running on `owid-staging`) will all be running on Node 18 instead of Node 16 after we update, but I don't think this is gonna be a huge problem since there were no big API removals in the new version.

TODOs:
(see also: https://github.com/owid/owid-grapher/issues/1096#issuecomment-1021384951 - but some steps in there, like the apt one, we probably don't want to do this time)
- [x] Upgrade owid-staging
	- [x] Install Node 18.16 using nvm and mark it as default
	- [x] Update the `/usr/local/bin/node` symlink
	- [x] Enable corepack so we get yarn "for free"
	- [x] Install `pm2` using Node 18
	- [x] Recreate a few `pm2` instances, such that they are then using Node 18
	- [x] Edit `/etc/systemd/system/pm2-owid.service` to use Node 18
	- [x] Test that everything works well
	- [ ] Update most instances to be using Node 18
- [x] Upgrade automated staging servers https://github.com/owid/ops/pull/71
- [ ] Upgrade owid-live

### CODE REVIEW

**Comment by Marigold** [comment]
> I haven't figured out yet how we can deploy this to a staging server, since we use the global Node 16 we have running. Have to figure that out at some point in the future...

@marcel Ping me if you want me to create PR in `ops` repo for node 18, I can spin up a staging server for this then.

**Comment by marcelgerber** [comment]
@Marigold yeah, that would be awesome actually. I would only deploy this after the offsite, but if we can have a staging server running off this branch that'd be great.

I see that in the current staging server setup we have v16 hardcoded: https://github.com/owid/ops/blob/ba32f8d7c58d4fd6dac2a14e377ac0c28111d827/templates/owid-site-staging/init.sh#L241-L246
A possibility there is also to source the `.nvmrc` file instead, which is actually also what we're doing in GH Actions (using `node-version-file` of https://github.com/actions/setup-node).

**Comment by Marigold** [comment]
Thanks for tips, I won't have time before offsite either, but can do it after.

**Comment by Marigold** [comment]
Tried it on `owid@mojmir-node-18` and it worked, though I had to retry `yarn install` because of the following error (likely not related to node18?)
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@cnakazawa/watch/-/watch-1.0.4.tgz - Not found
npm ERR! 404
npm ERR! 404  '@cnakazawa/watch@https://registry.npmjs.org/@cnakazawa/watch/-/watch-1.0.4.tgz' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

The site runs on http://mojmir-node-18/

**Comment by marcelgerber** [comment]
Converting to draft so I don't receive notifications about it every day while I'm away.
Planning to tackle this right after coming back (by upgrading staging servers).

**Comment by marcelgerber** [comment]
The steps performed in this update, and steps to update a legacy staging server to Node 18, are contained in here: https://www.notion.so/owid/2023-06-08-Upgrade-to-Node-18-252bf18a365946fa89a77b09951aef0c

**Pull request merged**
