### PR TITLE
feat(explorer): load partial grapher configs

### PR DESCRIPTION
**Pull request by sophiamersmann**
relates to #2313

### Summary

Fetch partial Grapher configs for indicators in explorers

### Walkthrough

- partial grapher configs are embedded on the explorer page and parsed when an explorer is created
- for now, only the partial grapher config of the first y-indicator is taken into account

### To do

- [x] Rename indicator to variable
- [x] Write up a strategy for scaling ([Notion page](https://www.notion.so/owid/Scaling-explorers-that-load-partial-grapher-configs-6ceb15be349a468aaa6900d856225e19?pvs=4))

### CODE REVIEW

**Comment by sophiamersmann** [comment]
Current dependencies on/for this PR:
* master
  * **PR #2332** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2332" target="_blank">Graphite</a> 
    * **PR #2333** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2333" target="_blank">Graphite</a> 
      * **PR #2349** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2349" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2349?utm_source=stack-comment).

**Review by marcelgerber — APPROVED** [review]
Nice work!

**Comment by sophiamersmann** [comment]
@sophiamersmann started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2349).

**Comment by sophiamersmann** [comment]
@sophiamersmann merged this pull request with [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2349).

**Pull request merged**
