### PR TITLE
Fix new author creation error on socials

### LINKED ISSUE #3576: Creating a new author fails on unenriched socials block
When creating a new author, [createGdocAndInsertIntoDb calls loadGdocFromGdocBase with an actual class instance](https://github.com/owid/owid-grapher/blob/82a849638cc8d0fc79cad163423f839e0cd8a82f/db/model/Gdoc/GdocFactory.ts#L104-L108). This means [Object.assign(gdoc, obj)](https://github.com/owid/owid-grapher/blob/82a849638cc8d0fc79cad163423f839e0cd8a82f/db/model/Gdoc/GdocAuthor.ts#L30) overrides `_enrichSubclassContent` with the base class default implementation, which fails to run the subcalss enrichment.

In the case of authors, this [enrichment](https://github.com/owid/owid-grapher/blob/82a849638cc8d0fc79cad163423f839e0cd8a82f/db/model/Gdoc/GdocAuthor.ts#L102-L105) is necessary for the proper parsing of ArchieML content, so this fails visibly. In other cases, it probably fails more silently.

Currently, this blocks the creation of authors, but we should also evaluate how this affects other types.

### PR DESCRIPTION
**Pull request by mlbrgl**
fixes #3576 

Both `GdocBase` instances and `OwidGdocBaseInterface` objects implement the same interface. However, GdocBase instances leak methods into `loadGdocFromGdocBase`, which override subclasses implementations.

With regards to overriding the `GdocAuthor` subclass with an instance of the parent class, three approaches have been reviewed:
- (selected) lodash `defaults` (see description in code)
- lodash `omitBy` (see description in code)
- GdocBase.toJSON: addresses a problem with similar roots

This PR only fixes GdocAuthor, but we should expand this to all Gdoc* subclasses created by the `loadGdocFromGdocBase` factory function.

### CODE REVIEW

**Comment by mlbrgl** [comment]
* **#3578** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3578?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @mlbrgl and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by mlbrgl** [comment]
@ikesau if you haven't started reviewing this, let me re-assign to @danyx, as he ran into a similar issue I believe. I'll assign you the next one.

**Review by ikesau — APPROVED** [review]
The comments are a bit verbose in my humble o, but I can confirm this fixes the issue 🙂 

tested by creating and saving an author page on master and this branch, inspected stored JSON in the DB

**Comment by ikesau** [comment]
If this is causing issues in other places, could you update all the other GdocBase inheritors to use `defaults` too? 🙂

**Comment by danyx23** [comment]
I like the verbose comments :) - thanks for fixing this, Matthieu! I agree that it would be nice to do this for all classes already in this PR

**Comment by mlbrgl** [comment]
yes, I'm indeed using long comments as a warning and a deterrent: the longer the comment the more I'll think about changing this line in the future 😄 

thank you both for the review, I've updated the other classes.

**Pull request merged**
