### PR TITLE
Migrate thank-you email to Cloudflare Pages functions

### PR DESCRIPTION
**Pull request by mlbrgl**
This PR migrates sending the thank-you email to a Cloudflare Pages function.

Screenshot 2024-01-02 at 19 03 28

_The part of the overall flow this PR deals with. See the full flow in the README._

Testing this locally is described in this PR, while testing on staging using Cloudflare previews is described in the next (#3055)

- [ ] (when deploying live) activate stripe webhook to /donation/thank-you in stripe dashboard

### CODE REVIEW

**Comment by mlbrgl** [comment]
Current dependencies on/for this PR:
* `master`
  * **PR #2956** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2956?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #2978** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2978?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #2998** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2998?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #3020** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3020?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/3020?utm_source=stack-comment).

**Review by danyx23 — APPROVED** [review]
Looks good! The one change I would maybe still make is for the UK donors to include the giftAid notice in the email always if it is a recurring donation. The current condition is more than 30 GBP but a recurring donation of even 10 GBP adds up over a year and would benefit from GiftAid.

I ran into yet another issue testing this locally but I don't want to hold up the review of this, maybe something is weird with my dev setup. Tested it on staging and it works as described.

**Comment by mlbrgl** [comment]
@danyx23 thanks for the suggestion, let me run it by @eoo-owid 

Let me know if you want to go over your local setup at some point, happy to help.

**Comment by eoo-owid** [comment]
I agree with @danyx23 re threshold for gift aid form 👍

**Comment by mlbrgl** [comment]
### Merge activity

* **Jan 11, 12:29 PM**: @mlbrgl started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/3020).

**Pull request merged**
