### PR TITLE
Error reporting in Cloudflare functions with Sentry

### PR DESCRIPTION
**Pull request by mlbrgl**
Add Sentry logging for /donation/* Cloudflare Pages functions routes.

At the time of writing, neither [bugsnag](https://github.com/bugsnag/bugsnag-js/issues/637) nor [slack](https://github.com/slackapi/node-slack-sdk/issues/1335) have official Cloudflare worker integrations.

Given the criticality of these routes, I favoured reliability and introduced a new logging app which has official Cloudflare support: https://developers.cloudflare.com/pages/functions/plugins/sentry/

We should switch to bugsnag whenever official support is available.

Testing:
- (ENV and SENTRY_DSN secrets are already defined for the preview environment in Cloudflare's "owid" project)
- temporarily disable the [Cloudflare Access rule](https://one.dash.cloudflare.com/078fcdfed9955087315dd86792e71a7e/access/apps/edit/d8c658c3-fd20-477e-ac20-e7ed7fd656de?tab=overview) by setting its  subdomain to `temp`
- send an empty JSON to https://donate.owid.pages.dev/donation/donate

-> an error is logged in sentry and an alert email is sent to [TBD]@ourworldindata.org (this will be configured when the use of Sentry is confirmed). Slack integration is only available on paid plans.

### CODE REVIEW

**Comment by mlbrgl** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3068?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #2956** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2956?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #2978** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2978?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #2998** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2998?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #3020** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3020?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #3055** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3055?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #3068** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3068?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/3068?utm_source=stack-comment).

**Comment by danyx23** [comment]
Hm. I don't love adding another service to our stack just for this. It's a bit annoying that neither bugsnag nor slack have CF compatible client libraries yet, but I think a bare-bones slack integration really doesn't need the client api as they have a pretty well designed http api. E.g. so send a message to slack channel is as simple as 
```http
POST https://slack.com/api/chat.postMessage
Content-type: application/json
Authorization: Bearer xoxb-your-token
{
  "channel": "YOUR_CHANNEL_ID",
  "text": "Hello world :tada:"
}
```

I'm kind of leaning towards a preference for a barebones slack message - but I'm happy to discuss the pros and cons of it in the site meeting later today if you like!

**Comment by mlbrgl** [comment]
sure, we can try this too if it is indeed very straightforward.

My only concern would be around reporting unhandled errors, but this is less of a concern here, since most of the functions bodies are wrapped in try {}.

I would be tempted to run them in parallel for a month or so, just to make sure we're not missing anything. If we end up with perfect symmetry, then yes, by all means, let's strip it down.

**Comment by mlbrgl** [comment]
see follow up in #3086

**Review by danyx23 — APPROVED** [review]
:shipit:

**Comment by mlbrgl** [comment]
### Merge activity

* **Jan 11, 12:29 PM**: @mlbrgl started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/3068).

**Pull request merged**
