### PR TITLE
Switch to GitHub Actions

### PR DESCRIPTION
**Pull request by MarcelGerber**
No longer using Travis.

Advantages:
* Builds are faster, since there's basically no startup time
* I've enabled an action that automatically prettifies files in a PR - let's test if this works
* Better integration in GitHub

Disadvantages:
* We can no longer use MySQL (or at least that isn't set up at the moment), but we're not doing anything with it anyway...

### CODE REVIEW

**Comment by breck7** [comment]
> * Builds are faster, since there's basically no startup time

Awesome. Do you have some ball park numbers?

> I've enabled an action that automatically prettifies files in a PR - let's test if this works

I think this could be really helpful for outside commits. I've definitely sent small PRs before to other projects and they'd get auto rejected because I wasn't running all the hooks on my machine.

One downside I can potentially foresee, if I'm understanding correctly, is if a PR is sort of a work in progress (like a draft PR, or you are responding to changes), and you have to deal with these server side commits getting made, pulling and merging them in.

> Better integration in GitHub

This could prove very useful! Have been meaning to explorer GitHub actions.

**Comment by MarcelGerber** [comment]
> Awesome. Do you have some ball park numbers?

Travis seems to take quite long to "Set up the VM" (about one minute maybe), whereas GitHub Actions just runs without much setup. Running the tests themselves is pretty similar for both. Just the yarn install is faster on Travis, but I can try to make that even faster.


> I think this could be really helpful for outside commits. I've definitely sent small PRs before to other projects and they'd get auto rejected because I wasn't running all the hooks on my machine.

It's also just useful for Hannah, with PRs like #539.



> One downside I can potentially foresee, if I'm understanding correctly, is if a PR is sort of a work in progress (like a draft PR, or you are responding to changes), and you have to deal with these server side commits getting made, pulling and merging them in.

Yes, that's true. I'm not sure if the Action runs on a draft PR, but dealing with the server-side commits can be a headache. When in doubt you can just force-push though. We can see how this plays out.

Another, maybe more relevant problem is that GitHub Actions doesn't run on this newly-pushed commit.
That's a [safeguard by GitHub](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token) to prevent recursive Actions, and I understand why it's there. There's not even some manual way to trigger another test run on that commit, though, and that's a bummer.
One way we could avoid that is to use the @owidbot token for Github Actions (and then probably also make sure that prettify doesn't run on its own commits).

**Comment by breck7** [comment]
> Yes, that's true. I'm not sure if the Action runs on a draft PR, but dealing with the server-side commits can be a headache. When in doubt you can just force-push though. We can see how this plays out.

Well, thinking more about it, I guess it should only commit if there's a change, which means prettify would have failed, so it would be helpful.

**Comment by MarcelGerber** [comment]
Alright I'm merging this now.
Any discrepancy between `testcheck:ci`, `testcheck`, `prettier`, `pretty-quick` etc. we can figure out later on.

Please also note that currently the automatic Prettify action is only running for pull requests, not (yet) for pushes to master.

**Pull request merged**
