### PR TITLE
Details on demand admin UI

### LINKED ISSUE #1472: Admin UI for managing DoDs

### PR DESCRIPTION
**Pull request by ikesau**
Resolves #1472 

A new table view in the grapher admin for DoD CRUD.

I didn't implement pagination but can if we think it's necessary.

https://user-images.githubusercontent.com/11844404/171907135-8f2d00dc-5f26-4875-8288-89510890d54b.mov

### CODE REVIEW

**Review by danyx23 — CHANGES_REQUESTED** [review]
If I duplicate a key then I get an error when the api backend is hit about a duplicate key but then the form resets and I have lost my edits - would be nicer to check and warn about this client side. 

In general, some error handling for API errors would be nice :)

**Comment by danyx23** [comment]
What kind of markup if any can be used in the content? I think (normal http) links would be good. Links to other details on demand I would disallow, no need to get recursive here. Maybe bold and italic?

**Comment by ikesau** [comment]
> What kind of markup if any can be used in the content?

I haven't made this decision yet, and there's no validation for it in the editor (yet?)

I was thinking just bold, italic, and links, which would be written with markdown syntax.

**Review by danyx23 — APPROVED** [review]
Looks good!

**Review by danielgavrilov — APPROVED** [review]
Nice! I only have nitpicky comments.

A search field might be nice once we start considering pagination (not sure if all authors do ⌘+F)

**Pull request merged**
