### PR TITLE
🎉 Change default author to 'Our World in Data team'

### PR DESCRIPTION
**Pull request by ikesau**
[See slack thread](https://owid.slack.com/archives/C040429G2SD/p1689688002774359?thread_ts=1689686397.684999&cid=C040429G2SD)

### CODE REVIEW

**Review by marcelgerber — COMMENTED** [review]
Should we maybe make it so the default is not persisted, and instead make it something like `authors ?? "Our World in Data team"` in presentation?

**Comment by ikesau** [comment]
@marcelgerber hmm yeah that's also an option. I don't have a super strong preference on it because the trade-off in having to add null-checks in a couple of places doesn't make it 100% more convenient.

Do you have a strong feeling on this, otherwise I'm tempted to just merge as is.

**Comment by marcelgerber** [comment]
Yeah I'm worrying a bit about the fact that, afaict, these migrated posts would go back to "Our World in Data" as the author once they are next updated from the gdoc, right? Unless the gdoc has been updated to reflect this change, of course.

**Comment by ikesau** [comment]
Yeah, this PR changes the default author when there's no author set in the gdoc, and when it's merged I would manually update any gdocs that have explicitly set `authors: Our World In Data` (e.g. https://docs.google.com/document/d/1TB59aGXgPRW37lAjvFGrSSDBoH38URvk6XfbCHHVqMY/edit) by removing the line entirely.

**Review by marcelgerber — APPROVED** [review]
Ah! Okay then

**Pull request merged**
