### PR TITLE
Migrate Wordpress post rendering

### PR DESCRIPTION
**Pull request by mlbrgl**
⚠️ This PR should not be merged as-is, but is a foundational step towards baking from the grapher DB.

This PR swaps the data source for the rendering of Wordpress posts from the Wordpress API to the synced grapher DB.

This change aims to be as surgical as possible, but still touches a lot of rendering code, including the
sitemap, algolia, blog index, country profiles, post previews and post rendering.

The next steps will be centered around the render functions in `formatWordpressPost()`, e.g. `renderProminentLinks()`, which relied on PHP code that is not part of the rendering pipeline anymore (e.g. `prominent-link.php`)

Note: I kept `getFullPost` and `getPostRowEnriched` separate but we could imagine merging them. I didn't want to propagate getFullPost edge cases to the parts of the codebase already relying on getPostRowEnriched. If this overall approach seems promising, we might decide to spend more time on refactoring for clarity, although the   opportunity cost needs to be carefully weighed given the expected temporary and frozen nature of this part of the codebase.

- [x] update owid-staging WP DB (used by staging-site servers)
- [x] [blog index](https://ourworldindata.org/latest): manually compare pages 1, 10 and 19
- [x] sitemap: live and staging sitemaps are identical
- [x] country profile: all render fine (with the caveat mentioned above about PHP rendering)

## Summary by CodeRabbit

- **New Features**
	- Enhanced post retrieval and rendering processes for better performance and accuracy.
- **Bug Fixes**
	- Fixed issues related to post data handling and rendering, ensuring more reliable content display.
- **Refactor**
	- Updated post data model and types for improved clarity and consistency across the application.
	- Streamlined post fetching and enrichment logic to enhance system efficiency.
- **Chores**
	- Removed outdated code and dependencies to maintain a clean and efficient codebase.

### CODE REVIEW

**Comment by mlbrgl** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3135?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #3126** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3126?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #3130** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3130?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #3135** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3135?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/3135?utm_source=stack-comment).

**Comment by mlbrgl** [comment]
@coderabbitai review

**Comment by mlbrgl** [comment]
@danyx23  rebasing onto the lastest DB access updates. Will reopen once I'm done.

**Comment by danyx23** [comment]
@mlbrgl thank you!

**Comment by mlbrgl** [comment]
@danyx23 ok done, good to go!

Re-baked with (in addition to the partial bake done on push): `yarn buildLocalBake http://staging-site-migrate-wp-post-rendering /home/owid/live-data/bakedSite --steps blogIndex gdocPosts wordpressPosts`

**Comment by danyx23** [comment]
Hey @mlbrgl, this looks good already. I checked it manually for a few pages and found that for example https://ourworldindata.org/books looks different. Is this expected at this point? Should I investigate these differences more?

I think it would be useful to rebase on top of current master so that we can use the screenshot tool with the new improments that Ike build that depend on the new events. I think `gt sync` should do the trick in the easiest way?

**Comment by mlbrgl** [comment]
@danyx23 thanks for the review! Yes this is to be expected at this point, so no need to spend time on investigating further. 

I also revised my thinking and I am now pursing a different approach as you know from our last conversation: [baking from rendered API response](https://www.notion.so/owid/2024-02-02-Baking-and-editing-Wordpress-API-snapshots-5c92d90280774d209b7aca22f65f71dd) (vs baking from unprocessed source HTML here)

So I'll retract this PR for now. Thanks again for spending time on this regardless! 🙏

**Pull request closed without merging**
