### PR TITLE
enhance: show "Copied" tooltip for a longer duration

### PR DESCRIPTION
**Pull request by marcelgerber**
I found the earlier implementation of the `CodeSnippet` tooltip fadeout to be a bit too quick, and have adapted it to be 1500ms (display) + 500ms (fadeout).

https://user-images.githubusercontent.com/2641501/207144195-93b2b93c-8683-4cf5-9020-1aebd83ffa9e.mp4

### CODE REVIEW

**Comment by ikesau** [comment]
My thinking behind the quick flash was more to show that _something_ had happened, not to be a real dialogue.

But I don't have any strong feelings on that. And if anything, I'd tell past-Ike that this should be done with actual HTML so that an ARIA status announcement could also be made, but, not a blocker either way.

**Comment by marcelgerber** [comment]
I personally find the very short flashing of the tooltip looks very uncommon, almost broken.
I like the 2-second one way more.

But let's maybe let someone else chime in and decide. @mathisonian, could you have a quick look at the video above and say which one you like more?

**Comment by mathisonian** [comment]
Just discussed this with @ikesau but posting here as well for visibility: 

IMO this is an improvement and I'd be happy to see it merged. It's possible that making the new duration _slightly_ shorter would feel better (e.g. changing the new display duration to something in the 750ms-1250ms range from 1500ms, my guess would be 1000ms) if you want to continue tweaking, but its a minor difference.

**Review by ikesau — APPROVED** [review]
lgtm 😊

**Pull request merged**
