### PR TITLE
datapages: "reuse our work" block

### PR DESCRIPTION
**Pull request by mlbrgl**
### <samp>🤖 Inspired by Copilot at 78d6d34</samp>

This pull request adds a new feature to the data page that shows how to reuse and cite the data and data page. It updated the `CodeSnippet` component to supports different themes and styles. It also updates the `DataPageJsonTypeObject` type to include citation fields. It modifies the files `site/blocks/code-snippet.scss`, `site/blocks/CodeSnippet.tsx`, `site/DataPageContent.scss`, `site/DataPageContent.tsx`, and `packages/@ourworldindata/utils/src/owidTypes.ts`.
- [x] is the branch up-to-date with master?
- [x] what problem is being solved here?
- [x] what solution has been chosen?
Reuse the `CodeSnippet` component, by adding a "light" theme.
- [x] are there other solutions?
- [x] is the scope clear, well-defined and small?
Add the last data page section: "Reuse this work freely"
- [x] could a flow chart / sequence diagram / architecture diagram help?
- [x] what is the happy path?
  - go to http://staging-site-datapages/admin/grapher/banana-production
  - scroll down to the bottom of the page
- [x] could the code be easier to read and understand?
- [x] can I help increase our confidence in the implementation by contributing tests?
- [x] should some errors be made more prominent?
- [x] what is missing, what should have been added / done / changed but hasn't?
  - [x] sticky nav link

### CODE REVIEW

**Comment by mlbrgl** [comment]
Current dependencies on/for this PR:
* master
  * **PR #2218** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2218" target="_blank">Graphite</a> 
    * **PR #2233** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2233" target="_blank">Graphite</a> 
      * **PR #2248** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2248" target="_blank">Graphite</a> 
        * **PR #2250** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2250" target="_blank">Graphite</a> 
          * **PR #2259** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2259" target="_blank">Graphite</a> 
            * **PR #2270** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2270" target="_blank">Graphite</a> 
              * **PR #2283** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2283" target="_blank">Graphite</a> 
                * **PR #2286** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2286" target="_blank">Graphite</a> 
                  * **PR #2303** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2303" target="_blank">Graphite</a> 
                    * **PR #2322** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2322" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2322?utm_source=stack-comment).

**Review by ikesau — APPROVED** [review]
Looks good! The `code-copy-button` isn't showing up but I think that's due to `navigator` not exposing the clipboard API when on an http page by default.

**Comment by mlbrgl** [comment]
@mlbrgl started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2322).

**Comment by mlbrgl** [comment]
[Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2322) rebased this pull request as part of a merge.

**Comment by mlbrgl** [comment]
@mlbrgl merged this pull request with [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2322).

**Pull request merged**
