### PR TITLE
Migrate donate Netlify function to Cloudflare (#proj-donor-page v2 option 1)

### PR DESCRIPTION
**Pull request by mlbrgl**
This is part of the migration of the donor flow from Netlify to Cloudflare, tracked in #2947.

This PR deals specifically with the migration of the `donate` function, which handles the creation of a Stripe checkout session upon clicking on "Donate" on /donate. See [README.md](https://github.com/owid/owid-grapher/blob/donate-cloudflare/functions/README.md) for a complete sequence diagram.

Additionally, it tackles:
- upgrading the Stripe API version from 2020-08-27 to 2023-10-16
- switching to [inline pricing](https://stripe.com/docs/products-prices/pricing-models#inline-pricing) for code-driven pricing (vs configuration in the Stripe dashboard)
- fixes reCAPTCHA validation
- a more isomorphic take on errors reported to the donor. Donation payloads are statically typed on the client and the server, and checked for proper type at runtime when received over the wire - all using a single type (thanks to Typebox). There is however no particular reporting of more general errors at this stage, beyond what might be surfaced in the Cloudflare panel. This needs to be addressed.

This PR also brings some reader-facing improvements:
- #2916
- a more customized checkout page (see [notion](https://www.notion.so/owid/2023-12-06-Donor-flow-repay-tech-debt-v2-option-1-2ef260e93f9a42f9a4aa2ad418831c60))
  - [x] custom text next to the submit button
  - [x] add a product image
  - removal of confusing “£0.01 mention” for monthly donations
  - “Donate £50” instead of “Pay” for one-time donations

Non-code actions:
- [x] add env variables to [Cloudflare dashboard](https://dash.cloudflare.com/078fcdfed9955087315dd86792e71a7e/pages/view/owid/settings/environment-variables) (production and preview environments)
- [x] (when deploying live) remove STRIPE_PUBLIC_KEY from .env (it is not used anymore)
- [x] (when deploying live) update DONATE_API_URL env var (`/donation/donate`)
- [ ] (when deploying live) update API version on stripe dashboard
- [ ] (when deploying live) merge https://github.com/owid/owid-donors/pull/1

Still unclear:
- [x] reporting errors happening in functions. EDIT: see #3068 
- [x] testing on staging server ~~(where to set env vars? Configure preview environment on Cloudflare dashboard?)~~
  - http://staging-site-donate-cloudflare/donate doesn't get past the form. I suspect this is because Stripe requires https when not running on localhost. I might either revive hans or install ngrok on staging-site-donate-cloudflare. EDIT: testing functions is better dealt with Cloudflare previews (see #3055)

Reference:
- see #2947 
- see [notion](https://www.notion.so/owid/2023-12-06-Donor-flow-repay-tech-debt-v2-option-1-2ef260e93f9a42f9a4aa2ad418831c60)

### CODE REVIEW

**Comment by mlbrgl** [comment]
Current dependencies on/for this PR:
* master
  * **PR #2956** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2956?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #2978** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2978?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #2998** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2998?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2998?utm_source=stack-comment).

**Review by danyx23 — COMMENTED** [review]
I tried this and it works. Some questions:
- I never saw a captcha (I tried with an incognito browser to check if this is because of cookies by google or similar but no captcha there either). Is that ok?
- I didn't get any email - is that expected?

Small nit: when you enter amount "0" you see the wrong error message (you should see the one that tells you the valid amount but instead it says you should enter an amount - i.e. it treats 0 as empty)
Another nit: there is a missing closing quote after the name in the summary message that is shown in stripe

**Comment by mlbrgl** [comment]
Thanks @danyx23!

> * I never saw a captcha (I tried with an incognito browser to check if this is because of cookies by google or similar but no captcha there either). Is that ok?

Yes, the threshold is set to the lowest bound so once your particular setup has been vetted (probably beyond a particular browser session, maybe with a mix of fingerprinting / IP / ...), it can be difficult to get another captcha (which is a desired feature, except for testing). I don't know the specifics of the scoring but pushing the threshold the other way temporarily + private browsing does show a CAPTCHA again. Also, verifications calls are going through in the console, and are registered in the dashboard a day later. So I think everything is in order.

Screenshot 2024-01-03 at 14 13 20


> * I didn't get any email - is that expected?

Yes, this is handled in the next PR up the stack #3020 

> Small nit: when you enter amount "0" you see the wrong error message (you should see the one that tells you the valid amount but instead it says you should enter an amount - i.e. it treats 0 as empty) Another nit: there is a missing closing quote after the name in the summary message that is shown in stripe

Thanks, fixed.

**Comment by mlbrgl** [comment]
### Merge activity

* **Jan 11, 12:29 PM**: @mlbrgl started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2998).

**Pull request merged**
