### PR TITLE
refactor(Variable): stop baking data and metadata from MySQL and use URLs to S3 instead

### PR DESCRIPTION
**Pull request by Marigold**
_Stop baking data and metadata and instead fetch those files from S3._

## Overview

Today our data flow looks like this. Grapher variables are rendered to JSON files in S3 by the `etl` (or backported by `datasync`). Those that are used in charts then get baked into our static Netlify site. Admin previews are an exception to keep latency high.

```mermaid
graph LR

upstream -->|etl| garden -->|etl| s3
garden -->|etl| mysql
mysql -.->|datasync| s3
s3 -->|baker| netlify --> browser
admin -->|edit| mysql
mysql --> admin -->|preview| staff-browser["browser (staff)"]

style netlify stroke-width:4
```

This change removes baking, and serves the live site from S3 directly:

```mermaid
graph LR

upstream -->|etl| garden -->|etl| s3
garden -->|etl| mysql
mysql -.->|datasync| s3
s3 --> cf-worker --> browser
mysql --> admin -->|preview| staff-browser["browser (staff)"]
admin -->|edit| mysql
cf-worker --> cf-cdn
cf-cdn --> cf-worker

style cf-worker stroke-width:4
style cf-cdn stroke-width:4
```

## Technical notes

In admin we still fetch metadata from MySQL. That's because `datasync` tool that replicates data & metadata to S3 has some latency (couple of seconds for most datasets) and we wouldn't see changes immediately. This might be refactored with partial grapher configs. It also means we are duplicating logic for creating metadata files in datasync and baker.

## Changes

* computed property `dataBaseUrl` is turned into normal property and set from env like `DATA_BASE_URL=https://catalog.ourworldindata.org/baked-variables/staging_grapher/`. Grapher then fetches data & metadata from `${dataBaseUrl}/data/${variableId}.json`
* note that metadata is still fetched from MySQL in admin (see [notes in code](https://github.com/owid/owid-grapher/pull/1939/files#diff-3e4306be594cb95ff9fe006c3c020b190c208882db96d4b8dbb9f38c501c8199R95), one day we'll get rid of it and point it to JSON)

### Checks before merging
* [x] `access-control-allow-origin: *` is present and iframes work fine (especially sdg-tracker)
* [x] charts in admin
* [x] charts on static website
* [x] charts on local
* [x] charts on staging
* [ ] latency comparable with live
* [ ] our CF worker can handle the load (don't know how to test that?)
* [ ] maybe experiment a bit more with our CF cache-control: we can consider decreasing the time we cache things, and then add a `must-revalidate` so the worker does a ETag check only
* [ ] fresh docker build works well
* [ ] (optional) gitpod works well

## Check after merging
* [ ] everything from above
* [ ] check how much we pay for [CF workers](https://dash.cloudflare.com/078fcdfed9955087315dd86792e71a7e/billing/billable-usage)

## TODO
* [ ] set `DATA_BASE_URL=https://catalog.ourworldindata.org/baked-variables/live_grapher/` on live server
* [ ] set `DATA_BASE_URL=https://catalog.ourworldindata.org/baked-variables/[staging_env]/` on all staging servers (it can be missing in local dev)

### CODE REVIEW

**Comment by Marigold** [comment]
@marcelgerber could you please take a look and tell me what you think about this? This looks like something that could potentially break a lot of things. One problem is that ETL is generating data and metadata json files so we need to make sure they're in sync. Another problem is that our deploys wouldn't be "atomic" anymore and changes to S3 files would be shown on our site without deploying it.

(I missed Netlify contract deadline, so we have another 5 months to make the decision. I'm not sure if there's any benefit from fetching data from S3 if that doesn't reduce our costs. We could also just skip this and stretch for Cloudflare pages.)

**Comment by Marigold** [comment]
Another thing that could be tricky is compression. JSON files are saved in S3 with gzip compression, but Cloudflare serves them with brotli compression (so it probably has to decompress gzip and compress with brotli before sending to client). I don't think this would have significant effect on latency (especially since most of our content is cached).

**Comment by Marigold** [comment]
[This PR](https://github.com/owid/cloudflare-workers/pull/7) with improved caching is probably essential for the switch. We need to be watching our S3 costs after switchover.

**Comment by Marigold** [comment]
[This PR](https://github.com/owid/cloudflare-workers/pull/7) with improved caching is probably essential for the switch. We need to be watching our S3 costs after switchover.

**Comment by Marigold** [comment]
I want to emphasise one thing (that could perhaps be controversial). We're not **baking variables metadata directly from MySQL** but take them from S3. Metadata can make it to S3 in two ways:
* ETL uploads metadata for all datasets (which is a majority now)
* `datasync` service watches for changes in MySQL and syncs its metadata to S3

Note that `datasync` only runs on live, so if anyone changes variable description on staging, they'll never see it updated there. This sounds like a bad thing, but variable metadata is rarely edited from admin these days (especially on staging).

**Comment by marcelgerber** [comment]
I'll get back to this.
Other than that, I don't quite know how much @larsyencken  was involved in these decisions, but would love for him to have a look at the overarching decisions in here, since he's very aware of our data-infrastructure decisions.

Ideally, we would also get a look from Daniel, but it's probably not worth waiting another 3 weeks.

**Comment by Marigold** [comment]
Yeah, it'd be awesome to get @larsyencken opinion. Honestly, I'm shitting my pants when I think about merging this. We're switching from static site to static site + S3 + Cloudflare Worker, so two more services to worry about that could somehow fail (or get crazily expensive). It really deserves a third pair of eyes.

**Comment by larsyencken** [comment]
Started looking at this, will take me a little while to be across it.

**Comment by Marigold** [comment]
(I've just rebased & deployed it to https://playfair-owid.netlify.app/, you can check it there.)

**Comment by larsyencken** [comment]
I've spent most of my review time not looking at this code at all, but trying to understand the architecture that's been developed here. (In retrospect, Mojmir and I should have paired on it and discussed, it would have saved me heaps of time!)

## General concerns

A general concern is that the ETL and Grapher are today, even before this PR, deeply coupled, yet they live in separate codebases and have separate dev environments. It's not trivial to replicate what we have in prod locally in dev any more.

Another concern about where we already are today is that, with all our use of object storage, our dev and staging environments are no longer properly isolated.

Our use of object storage in S3 is also not properly isolated, with buckets being reused for multiple purposes, and prod buckets not being separated from staging or dev buckets.

## Moving towards an API

I would prefer us to use a different URL scheme for our JSON data, one that is more future proof and reflects our path towards having a data api. For example, instead of:

https://catalog.ourworldindata.org/baked-variables/live_grapher/data/1234.json
https://catalog.ourworldindata.org/baked-variables/live_grapher/metadata/1234.json

I would recommend a URL scheme more like:

`# production`
https://api.ourworldindata.org/v1/variables/1234.data.json
https://api.ourworldindata.org/v1/variables/1234.metadata.json
https://api.ourworldindata.org/v1/datasets/342.json

`# dev`
http://localhost:3031/api/v1/variables/1234.data.json

Later we may make this API dynamic. In dev we can use nginx to serve this to a local folder. In staging we can do something similar.

## Rollout strategy

I would prefer to get the dev and staging environments isolated and right first before prod, instead of prod first and then the others. That approach gives us much more control to experiment and improve the setup.

For this to work, we probably need to be creating new JSON data bundles that get fetched, untarred and saved to a space on first `make up` and sync'd on `make refresh`.

Ideally, there should also be a new `make up.with-etl` that spins up the entire stack, including ETL services, for data managers and also for yourself.

---

Sorry to be giving all this feedback so late. I think this is the right direction for us to be going in, I just don't think starting with prod data is the best way. Let's chat as soon as you're back @Marigold !

**Comment by larsyencken** [comment]
Closing now that we have a new approach.

**Pull request closed without merging**
