### PR TITLE
💄 (grapher) remove isExplorable option

### PR DESCRIPTION
**Pull request by sophiamersmann**
> [!WARNING]  
> Db tests are failing.

Just a little bit of cleanup. Removes the `isExplorable` property from Grapher's config and the `isExplorable` column from the `charts` table.

The config schema states that the `isExplorable` property is not in use and should be removed. I then noticed that the `charts` table has a column called `isExplorable` that also isn't in use, so I decided to remove it too.

Technically, this is a breaking schema change, but there is no real code change, so I guess it's okay not to increase the schema version etc.

### CODE REVIEW

**Comment by sophiamersmann** [comment]
* **#3323** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3323?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @sophiamersmann and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by marcelgerber — APPROVED** [review]
Nice one!

For reference, I'm pretty sure that this property was used [for the circa-2019 old explorer](https://explorer-owid.netlify.app/explore), and is therefore absolutely safe to remove at this point.

**Comment by sophiamersmann** [comment]
Ah, that's good to know! It's so cool that the link to the everything explorer is still working :)

Do you have any idea why the db test might be failing? It doesn't make sense to me...

**Comment by marcelgerber** [comment]
Ah, sadly the DB tests are still failing.

Let's summon @danyx23!

**Comment by danyx23** [comment]
A wild Daniel appears!

Ok this is one of these cases where, after you fix it, you really don't understand how this can ever have worked before. I don't get it. Whatever, the issue is fixed now! 🎉 ... 😬

**Comment by sophiamersmann** [comment]
haha, thanks a lot for looking into this!

**Pull request merged**
