### PR TITLE
enhance(dp): dark header

### PR DESCRIPTION
**Pull request by mlbrgl**
_Data pages_

- dark header

- full width separation after key information

### CODE REVIEW

**Comment by mlbrgl** [comment]
Current dependencies on/for this PR:
* master
  * **PR #2356** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2356" target="_blank">Graphite</a> 
    * **PR #2359** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2359" target="_blank">Graphite</a> 
      * **PR #2365** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2365" target="_blank">Graphite</a> 
        * **PR #2368** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2368" target="_blank">Graphite</a> 
          * **PR #2370** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2370" target="_blank">Graphite</a>  👈
            * **PR #2360** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2360" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2370?utm_source=stack-comment).

**Comment by mlbrgl** [comment]
Current dependencies on/for this PR:
* master
  * **PR #2356** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2356" target="_blank">Graphite</a> 
    * **PR #2359** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2359" target="_blank">Graphite</a> 
      * **PR #2365** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2365" target="_blank">Graphite</a> 
        * **PR #2368** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2368" target="_blank">Graphite</a> 
          * **PR #2370** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2370" target="_blank">Graphite</a>  👈
            * **PR #2360** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/2360" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2370?utm_source=stack-comment).

**Review by ikesau — APPROVED** [review]

**Comment by mlbrgl** [comment]
@mlbrgl started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2370).

**Comment by mlbrgl** [comment]
@mlbrgl merged this pull request with [Graphite](https://app.graphite.dev/github/pr/owid/owid-grapher/2370).

**Pull request merged**
