### PR TITLE
✨ add autofocus to homepage search and data catalog

### PR DESCRIPTION
**Pull request by ikesau**
Implements https://github.com/owid/owid-grapher/issues/3982

Avoids the issue of having to recreate the google.com behaviour on the homepage search by disabling the dropdown panel until there the user has typed something.

### CODE REVIEW

**Comment by ikesau** [comment]
@larsyencken I realized while investigating for your questions it was simple enough to just try making the changes and see how it feels in staging.

**Review by larsyencken — APPROVED** [review]
Super nice! This is a subtle change, but I feel like it would increase the number of searches people do, and it's really nice for power users.

**Comment by ikesau** [comment]
Yeah, I agree that removing suggested searches is significant, seeing as they're each among our top 10 searched terms according to Algolia analytics. 

Correlation != causation, these terms might just be popular in their own right, but maybe it's reason to think a bit about what we think the value of suggesting searches is, and how much of that value we lose by removing them.

i.e. do suggested searches increase the likelihood that someone will submit a search, which increases the likelihood that they'll find interesting content? or do suggested searches only make it slightly faster to submit a search without affecting overall search rates.

Changing arrow key behaviour would be harder to test, but yeah it's for reasons like that that people disable autofocus in the browsers.

**Comment by marcelgerber** [comment]
This is hard to test for, of course, but my hunch is that Suggested Searches give some idea of what to search for in our publication.

Obviously there's also other such hints on the homepage - the search box placeholder text, the row of topic pages at the top, etc. - but it's probably nice to have that right in the users face when they are attempting to search?

**Comment by ikesau** [comment]
@larsyencken how do you want to proceed? Autofocus on the catalog only?

**Comment by larsyencken** [comment]
> @larsyencken how do you want to proceed? Autofocus on the catalog only?

I'm happy for you to split out and ship the catalog improvement. For the homepage, I made a Slack thread with you, me and Joe to make a call.

**Comment by ikesau** [comment]
The decision has been to not autofocus the homepage 👍

**Pull request merged**
