### PR TITLE
🐛 (grapher) show timeline on table tab if necessary

### LINKED ISSUE #3174: Grapher's data table sometimes doesn't show all plotted data
## Description

- In case of [this StackedBar chart](https://ourworldindata.org/grapher/annual-reported-ai-incidents-controversies), the data table only shows the start and end year – but there is no way to view intermediate years

## Expected behaviour

- Either show the timeline on the table tab, so that one can select other years
- Or rethink our table in such cases

## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/annual-reported-ai-incidents-controversies
2. Note that it shows data from 2012-2021
3. Switch to the table
4. Note that data for 2012 and 2021 is shown, without the possibility to view intermediate data points

## Screenshots

Screenshot 2024-02-06 at 10 25 48

Screenshot 2024-02-06 at 10 26 02

### PR DESCRIPTION
**Pull request by sophiamersmann**
- fixes #3174 

## Summary

- Stacked area and bar charts as well as line charts show multiple years at once (since time is plotted on the x-axis)
- If the timeline is hidden, the chart thus shows the whole range of data points (all values from start time to end time), but the table only shows data points for the start and end time exclusively
- This PR makes it so that the timeline is always shown on the table tab for stacked bar/area and line charts
- Datasette: [Stacked area/bar and line charts where the timeline is hidden](https://datasette-public.owid.io/owid?sql=select%0D%0A++id,%0D%0A++slug,%0D%0A++type%0D%0Afrom%0D%0A++charts%0D%0Awhere%0D%0A++json_extract(config,+%22$.hideTimeline%22)+is+true%0D%0A++and+(%0D%0A++++type+%3D+'StackedBar'%0D%0A++++or+type+%3D+'StackedArea'%0D%0A++++or+type+%3D+'LineChart'%0D%0A++))

## Data cleanup

- [x] http://staging-site-table-timeline/grapher/natural-disasters-by-type: Set `timelineMinTime` and `timelineMaxTime` to what's currently set as `minTime` and `maxTime` so that we don't include data in the table that is not plotted 
- [x] Turn [these two charts](http://datasette-private/owid?sql=select%0D%0A++id,%0D%0A++slug,%0D%0A++type%0D%0Afrom%0D%0A++charts%0D%0Awhere%0D%0A++json_extract(config,+%22$.hideTimeline%22)+is+true%0D%0A++and+type+%3D+'LineChart'%0D%0A++and+json_extract(config,+%22$.minTime%22)+%3D+json_extract(config,+%22$.maxTime%22)) into "proper" discrete bar charts (they're line charts under the hood)
    - [x] http://staging-site-table-timeline/grapher/covid-tests-per-confirmed-case-exemplars
    - [x] http://staging-site-table-timeline/grapher/share-of-global-consumption-based-co-emissions-and-population

### CODE REVIEW

**Comment by sophiamersmann** [comment]
* **#3458** <a href="https://app.graphite.dev/github/pr/owid/owid-grapher/3458?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @sophiamersmann and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by marcelgerber** [comment]
Hm, what's super weird about this is that changing the timeline selection on the table tab changes what's shown on the chart tab - but then back on the chart tab, there's no way to "go back" to the initial timeline selection.

Assuming that the decision to hide the timeline has been made consciously, this shouldn't be possible.

**Comment by sophiamersmann** [comment]
I'm not sure what you mean. Do you have an example chart?

**Comment by marcelgerber** [comment]
I think it's gonna be everyone? See the video (in there, it's http://staging-site-table-timeline/grapher/natural-disasters-by-type).

https://github.com/owid/owid-grapher/assets/2641501/5ad4c4a2-ae92-4078-9505-033c4efe20d0

**Comment by sophiamersmann** [comment]
Ah, now I know what you mean. Hmm..

**Comment by sophiamersmann** [comment]
Hey @marcelgerber, thanks for the review! There was another bug here where a line chart turned into a discrete bar chart when you dragged the handles onto the same year on the table tab. I updated the `isLineChartThatTurnedIntoDiscreteBar` to fix this. Can you have a quick look to see if that makes sense to you? 😇

**Review by marcelgerber — APPROVED** [review]
Good on you for catching that case! 🙌🏻

**Pull request merged**
