### PR TITLE
fix: make country selection top-to-bottom, left-to-right

### PR DESCRIPTION
**Pull request by larsyencken**
Switch from flex box for entity selector to using ul columns with a media query.

This is because countries were spilling left-to-right before top-to-bottom, a highly unintuitive sort order for people to look through. A media query approach was taken because flexbox columns would only solve this if the container had fixed height.

See: https://www.notion.so/owid/List-countries-vertically-instead-of-by-rows-in-grapher-country-selector-ad9fbd8b86c04e61bf58b68dd5e1bade

### CODE REVIEW

**Comment by larsyencken** [comment]
## How to test

1. Browse to a chart with a country selector, like: http://localhost:3030/grapher/average-childbearing-age
2. Click "Add Country"
3. Verify that the country list goes top-to-bottom before starting a new column, and that (in normal width browser) it takes up two columns.
4. Verify that it shrinks to just one column if the window is made more narrow.

**Review by MarcelGerber — APPROVED** [review]
Nice and simple, I like it!
I quickly removed a now-superfluous `flex` style that we no longer need, so we don't trip over it in the future.

**Comment by MarcelGerber** [comment]
I'm not sure if this could also be nicely solved using grid styles (I'm not very acquainted with them), but that's something to maybe explore in the future.
Gonna merge this for now!

**Comment by larsyencken** [comment]
Thanks Marcel! 🙌

**Pull request merged**
